// Latvian descriptions and tournament names.
// The pools are intentionally smaller than the English source: only the strongest
// translations are included. Keep the 120-minute creation defaults complete.

// MottoWidget: partial descriptions pool.
// CreateFlow: entire Latvian descriptions pool for regeneration.
export const DESCRIPTIONS_INITIAL: string[] = [
  'Uzvarēt ir vāji. Nospēlēt neizšķirti — dievišķi.',
  'Punkti tabulā ir labi. Papildu 30 treniņa minūtes — kosmiski.',
  'Draudzības mači nāk un iet. Ekrānšāviņi ar turnīra tabulu paliek.',
  'Punkti ir gaistoši. 30 papildu treniņa minūtes — nemirstīgas.',
  'Turnīra tabulas nāk un iet. Papildu treniņš – paliek.',
  'Dzīve ir īsa. Mačiem jābūt garākiem.',
  'Ceļš uz slavu ir bruģēts ar 120 minūšu drāmu.',
  'Spēļu kalendārs ir automātisks. Drāma jārīko pašam.',
  'Visi ir draudzīgi līdz brīdim, kad tiek atjaunota turnīra tabula.',
  'Domā ārpus 90 minūtēm.',
  'Visi menedžeri ir ģēniji. Kļūdās tikai spēles dzinējs.',
  'Vienīgā vieta, kur neuzvarēt pēc 90 minūtēm ir teiksmaina taktika.',
  'Daži te nāk izklaidēties. Citi — atgādināt, kurš ir saimnieks.',
  'Vieni sapņo par uzvaru. Citi iet pāri līķiem, lai negūtu punktus pamatlaikā.',
  'Vienīgā vieta, kur par laikus nepabeigtu darbu tevi uzslavē.',
  'Vieta, kur uzvarēt ir katastrofāli, bet izniekot visas savas iespējas — dievišķi.',
  'Kas vienam menedžerim neizšķirts, otram menedžerim — treniņš.',
  'Īstais treniņš sākas tikai pēc 90. minūtes.',
  'Menedžeriem, kuriem ar 90 minūtēm vienkārši nepietiek.',
  'Nāc, ja tev ar 90 minūtēm vienkārši nepietiek.',
  'Daži dzenas pēc trofejām. Citi — pēc maģiskās papildu pusstundas.',
  'Kur izcils plāns sastop katastrofāli nepareizus mača notikumus.',
  'Lai tev teiksmaina forma un neeksistējošas traumas.',
  'Lai tava izturība ir teiksmaina, bet viduslīnija — draņķīga.',
  'Lai tava vidējā līnija ir draņķīga, bet aizsardzība — dievišķa.',
  'Atceries: tas ir draudzības mačs tikai līdz brīdim, kamēr kāds zaudē.',
  'Lai izdodas viss iecerētais un neaizmirsti netrāpīt pa vārtiem.',
  'Nāc pēc punktiem. Paliec minūšu dēļ.',
  'Nožēlojamas 90 minūtes var būt teiksmainas 120.',
  'Kas notiek pamatlaikā, paliek pamatlaikā.',
  'Situācija saasinājusies līdz 120. minūtei.',
  '90 minūtes tā vienkārši nebeidzas...',
  'Sāc lēni, beidz vēlu.',
  'Svarīgi nav tas, kā sāc, bet gan tas, kā nepabeidz.',
  'Spēlē vāji. Nekad nepabeidz.',
  'Atbilde ir papildu minūtes. Kāds bija jautājums?',
  'Atbilde ir papildu minūtes. Kāds bija jautājums?',
  'Uzvara paredzēta lūzeriem 💪',
  'Stipri Hattrick spēlētāji pabeidz pēdējie.',
  'Leģendāri Hattrick spēlētāji beidz vēlu.',
  'Lai tavs nākamais draudzības mačs ilgst nedēļu!',
  'Dažas minūtes ir svarīgākas par citām.',
  'Vieniem tas ir neizšķirts, citiem — kosmiska uzvara pār pamatlaiku.',
  'Bez sāpēm nav minūšu.',
  'Ceļš uz slavu bruģēts ar 120 minūšu neizšķirtiem.',
  'Tu netrāpi 100% sitienu, kurus neizpildi. Tāpēc neizpildi tos.',
  'Tiekamies kosmiskajā papildlaikā!',
  'Katra papildu minūte dod vairāk laika paraudāt par savām kļūdām.',
  'Pārdzīvo savas taktiskās kļūdas 30 minūtes ilgāk!',
  'Pasaules klases iespēja 120 minūtes nožēlot savas taktiskās kļūdas.',
  'Trofejas – tas ir labi, bet iespēja pazīmēties ar to citiem — kosmiski.',
  'Uzvarētāji dodas mājās. Tie, kas spēlē neizšķirti, paliek.',
  'Dodiet man papildu 30 minūtes, nevis punktus — jebkurā brīdī.',
  '90 minūtes smaga darba, 30 minūtes papildu treniņa – kā var to negribēt?',
  'Izturība ir tikai cipars, līdz brīdim, kad pienāk 100-tā minūte.',
  'Visas minūtes ir svarīgas, bet dažas minūtes ir svarīgākas par citām.',
  'Lai dzīvo Hattrick, futbols, alus un papildu 30 minūtes ar to visu!',
  'Tikai dažu lietu dēļ dzīvē ir vērts cīnīties papildu 30 minūtes – alus un treniņš ir starp tām.',
  'Stresa nav — ja vien nesāc uzvarēt pamatlaikā.',
  'Stresa nav — ja vien nesāc uzvarēt pamatlaikā.',
  'Kas notiek papildlaikā... paliek treniņa rezultātos.',
  'Opā! Atkal aizspēlējosies līdz papildlaikam.',
];

// CreateFlow: partial tournament names pool.
export const EXTRA_TIME_TOURNAMENT_NAMES: string[] = [
  'Dievišķā neizšķirta ielūguma turnīrs',
  'Diženo papildu minūšu līga',
  'Utopiskā papildlaika biedrība',
  'Kosmiskā laika līga',
  'Teiksmainās 120. minūtes kauss',
  'Titāniskā treniņa iespēja',
  'Pārdabiskās izturības kauss',
  'Izcilo papildlaika meistarsacīkstes',
  'Iespaidīgā papildu pusstunda',
  'Teicamo papildlaika ielūguma turnīrs',
  'Izcilo neizšķirtu biedrība',
  'Pēdējo 30 minūšu turnīrs',
  'Ceļš uz 120. minūti',
  'Papildlaika brālība',
  'Papildu minūšu ordenis',
  'Pamatlaika pretestības līga',
  'Dzīve sākas pēc 90',
  'Mačs, kas negribēja beigties',
  'Pēkšņais papildlaiks',
  'Negaidītās papildu 30 minūtes',
  'Kur fani ir līksmi un sponsori dejo ielās!',
  'Kur fani ir līksmi un sponsori dejo ielās!',
];

// CreateFlow: partial universal tournament names pool.
export const UNIVERSAL_TOURNAMENT_NAMES: string[] = [
  'Mēs esam mierīgi, apmierināti un priecīgi',
  'Līksmie fani un apmierinātie sponsori',
  'Sponsori dejo ielās',
  'Sponsori sūta mīlestības vēstules',
  'Pazemosim viņus!',
  'Mierīgo sponsoru ielūguma turnīrs',
  'Saniknoto sponsoru kauss',
  'Izcili augstas cerības',
  'Miermīlīgā komandas gara turnīrs',
  'Stresa nav — ielūguma turnīrs',
  'Mazliet pārspīlētu cerību līga',
  'Taisnīgie un krietnie',
  'Neģēļi, nešpetni tipi un psihopāti',
  'Mums ir priekšrocība 🏆',
  'Viņiem ir priekšrocība 🏆',
  'Katru dienu šajā turnīrā var uzskatīt par bonusu',
  'Jātiecas pēc titula!',
  'Būs grūti jācīnās kauss',
  'Mēs esam favorīti kauss',
  'Mēs zaudēsim — ielūguma turnīrs',
  'Labāk nemaz nerādīties',
  'Mūžīgā nožēla par taktiskajiem norādījumiem',
  'Titāniskās izturības līga',
  'Dievišķo neizšķirtu ielūguma turnīrs',
  'Mītiskās vidējās līnijas trofeja',
  'Pārdabiskās formas turnīrs',
  'Pasaules klases treniņa kauss',
  'Apmierinošu rezultātu federācija',
  'Draņķīgās vārtu gūšanas ielūguma turnīrs',
  'Neeksistējošā uzbrukuma līga',
  'Vāji spēlē, nekad nepabeidz — izaicinājuma kauss',
  'Sāc lēni, beidz vēlu — līga',
  'Draugi līdz sākuma svilpei',
  'Uzvara domāta zaudētājiem 💪',
  'Viens punkts ir gana — līga',
  'Vēl viens neizšķirts',
  'Perfekti noslīpētu attaisnojumu biedrība 💎',
  'Alus pirms analīzēm kauss 🍺',
  'Mēs analizējam analīzes kauss 🍺',
  'Nākamā rīta attaisnojumu līga 🍻',
  'Nejaušais meistardarbs — kauss ⚽️',
];

// CreateFlow: complete 120-minute descriptions pool for the initial default.
export const TOURNAMENT_DEFAULT_120MIN_DEFAULTS: string[] = [
  'Presings, 5-5-0 un 100% aizsardzība — tāds ir mūsu dreskods.',
  'Divu stundu ballīte ar presingu, 5-5-0 un 100% aizsardzību.',
  'Presings, 5-5-0, pilnīga aizsardzība un tavs sliktākais standartu izpildītājs – recepte labam treniņam.',
  'Lai slavēti ir 5-5-0, presings un standartu izpildītājs, kurš nespēj trāpīt pa bumbu!',
  'Sargā visu. Negūsti vārtus. Pulkstenī skaties tikai pēc 90. minūtes.',
  'Tavam draņķīgajam standartu izpildītājam beidzot ir pielietojums: noturēt maču dzīvu pēc 90. minūtes.',
];

// TournamentView: full 120-minute pool, built from all required defaults and
// a small selection of the strongest additional lines.
export const TOURNAMENT_DEFAULT_120MIN: string[] = [
  ...TOURNAMENT_DEFAULT_120MIN_DEFAULTS,
  'Uzvara ir vāja. Neizšķirts — dievišķs.',
  'Treniņš sākas pēc 90. minūtes.',
  'Nožēlojamas 90 minūtes. Utopiskas 120.',
];

// TournamentView: complete Latvian tournament descriptions pool.
// MottoWidget: partial descriptions pool.
// CreateFlow: complete descriptions pool for regeneration.
export const TOURNAMENT_DEFAULT: string[] = [
  'Uzvarēt ir vāji. Nospēlēt neizšķirti — dievišķi.',
  'Viena menedžera neizšķirts ir otra menedžera treniņš.',
  'Svilpe 90-tajā minūtē ir tikai ieteikums.',
  'Dzīve ir īsa. Mačiem jābūt garākiem.',
  'Neizšķirts ir vairāk vērts par veselu mūžu uzvaru.',
  'Kur futbols mūs vieno, bet vārti mūs šķir.',
  'Līdz 90. minūtei mēs esam draugi. Pēc tam — tikai konkurenti.',
  'Kur satiekas svešinieki un rodas leģendas.',
  'Dažādi notikumi, dažādi klubi, viena atkarība.',
  'Kur futbols saved kopā, bet sacensības paveic pārējo.',
  'Kur dzimst izcili izaicinājumi un vēl izcilāki attaisnojumi.',
  'Menedžeri, optimisti un leģendāri attaisnojumi.',
  'Futbols, statistika un labas noskaņas — neticamā līdzāspastāvēšanā.',
  'Uz laiku apvienojušies pret spēles dzinēju.',
  'Katrs menedžeris ir ģēnijs, un spēles dzinējs vienmēr kļūdās.',
  'Kur izcils plāns sastop idiotiskus spēles notikumus.',
  'Futbols, izklājlapas un viltus optimisms.',
  'Sāc lēni, beidz vēlu.',
  'Kur futbols satiekas ar izklājlapām un kaut kā kļūst par sportu.',
  'Skaistā spēle, kur katra pēdējā brīža kļūda ir rūpīgi vadīta.',
  'Katrs rezultāts rada jaunu teoriju.',
  'Tā ir draudzība… līdz sākuma svilpei.',
  'Pietiekami nopietni, lai rūpētu. Pietiekami draudzīgi, lai smietos.',
  'Turnīra tabula ir svarīga. Treniņš — vēl svarīgāks.',
  'Katra sezona sākas ar cerībām un beidzas ar dzērienu.',
  'Daži dzenas pēc trofejām. Citi — pakaļ tiem, kas dzenas pēc trofejām.',
  'Lai tavi izcilie plāni kaut kā pārdzīvo sadursmi ar realitāti.',
  'Vēl viena sezona, vēl viena iespēja visu izdarīt nepareizi.',
];

// CreateFlow: entire localized tournament names pool.
export const TOURNAMENT_NAMES: string[] = [
  ...EXTRA_TIME_TOURNAMENT_NAMES,
  ...UNIVERSAL_TOURNAMENT_NAMES,
];

// CreateFlow: entire localized descriptions pool.
// MottoWidget: partial descriptions pool.
export const DESCRIPTIONS: string[] = [...DESCRIPTIONS_INITIAL, ...TOURNAMENT_DEFAULT];
