export const DESCRIPTIONS: string[] = [
  'This tournament is extra-terrestrial. 👽👾🛸',
  'Every additional minute is a magnificent chance to regret your match orders.',
  'Every additional minute is a brilliant chance to regret your match orders.',
  'Regret your match orders magnificently.',
  'World class opportunity to not finish on time.',
  'Extra-terrestrial opportunity to not finish on time.',
  'World class opportunity to regret your match orders for 120 minutes.',
  'This tournament is more magnificent than we would have decency to admit.',
  'Winning is magnificent. Not scoring is utopian.',
  'The trophy is solid, but the bragging rights are extra-terrestrial.',
  'A tournament so utopian even you signed up.',
  'Finishing on time is not welcome here.',
  'Give me extra 30 minutes above points any day.',
  'Points are excellent. Extra 30 minutes are titanic.',
  '90 minutes of hard work, 30 minutes of training, a lifetime of regret.',
  'The only tournament where not winning after 90 minutes is a strategic masterclass.',
  'Stamina is just a number until you run out of it after 105 minutes.',
  'Some teams came for fun. Others came to remind everyone who is boss.',
  'Friendlies are temporary. Screenshots of the standings are forever.',
  'Points are temporary. 30 minutes of training is eternal.',
  'The standings are temporary. Training gains are eternal.',
  'Life is short. Matches should be longer.',
  'The road to glory is paved with 120-minute drama.',
  'The road to glory is paved with 120-minute drama.',
  'The only tournament where not winning after 90 minutes is a strategic masterclass.',
  'A gathering of future champions and current excuses.',
  "Keep still and don't move until referee says it's overtime",
  'Where your score is counted by a magical device on referees left wrist.',
  'Everyone is friendly until the standings are published.',
  'Winning is excellent. Trash talking is extra-terrestrial.',
  'The schedule is automatic. The drama is not.',
  'May your players stay healthy and your opponents stay offline.',
  'Keep your friends close and your opponents drunk.',
  'The road to glory starts with a friendly and ends with statistics.',
  "Let's play some imaginary football and judge each other.",
  'Where legends are made and statistics are born.',
  'No spreadsheets were harmed in the creation of this tournament.',
  'Some call it a friendly tournament. We call it serious business.',
  'The only thing stronger than these teams is our false optimism.',
  "If your stamina isn't solid, your plans are non-existent.",
  "If you're reading this, you're already behind in the standings.",
  'May R be kind to you.',
  'Play fair, have fun, do not win.',
  'The grass is virtual, but the sweat is real.',
  'Contains traces of ambition and excessive confidence.',
  'So tell me again how your best player got injured.',
  'The standings never lie, but they occasionally enjoy a casual half-truth.',
  'Welcome to the tournament where every manager is a tactical genius.',
  'Play fair, collect points, drink beer, make friends.',
  'We are here to declare war versus those who finish on time.',
  'Finally an absolutelly normal tournament with no grudges involved.',
  'Some teams dream of victory. Others work hard to not score in regular time.',
  'The path to greatness begins with clicking "Join Tournament".',
  'Where every minute counts, but some count more than others.',
  'Here is to Hattrick, to football, to beer and to 30 extra minutes.',
  'Only a few things in life are good enough to fight for extra 30 minutes.',
  'Winning is disastrous. Not scoring is divine.',
  'Winning is disastrous. Not scoring is divine.',
  'May your midfield be formidable and your stamina supernatural.',
  "One man's draw is another man's training.",
  "The only place that rewards those who can't finish on time.",
  'The only place where you will be rewarded for not finishing on time.',
  'The only place where you will be rewarded for not finishing on time.',
  'Created for managers who think 90 minutes is simply inadequate.',
  'Join us if think 90 minutes is simply inadequate.',
  'Why settle for a 90 min drama when you can have 120 minutes of eternal suffering?',
  'A mythical tournament for managers with extra-terrestrial patience.',
  'Some teams chase trophies. Others chase that magical extra half-hour.',
  'Give your opponent a point and you shall be rewarded magnificently.',
  'Where brilliant planning meets disastrous game events.',
  'The road to glory is paved with 120-minute draws.',
  'May your form be excellent and your injuries non-existent.',
  'Training starts after 90',
  'No pressure, just eternal recognition among a very specific group of people.',
  'May your midfield be divine and your team spirit in heaven.',
  'Scientifically optimized extra minutes factory.',
  "Remember: it's only a friendly until you lose.",
  'A celebration of football, community, and questionable characters.',
  'The finest collection of future champions currently available.',
  "Good luck, have fun, and don't forget to arrange your friendly.",
  'We want some extra',
  'This placeholder description is here because nobody wanted to write a real one.',
  'The greatest tournament in this exact browser tab.',
  'Give us more minutes',
  'The finest collection of minute addicts',
  'The finest collection of minute addicts',
  'Come for the points. Stay for the extra minutes.',
  'If this tournament had had those extra 30 mins it would be magnificent by now',
  'A tournament so prestigious it already has a default description.',
  'Points are excellent. Extra 30 minutes are titanic.',
  '90 minutes of hard work, 30 minutes of training, a lifetime of regret.',
  'The only tournament where not winning after 90 minutes is a strategic masterclass.',
  'Stamina is just a number until you run out of it after 105 mins.',
];

export const TOURNAMENT_NAMES: string[] = [
  'Awesome Great Tournament 🤩',
  'The Battle for Extra Minutes',
  'The Most Important Tournament Today™',
  '120 Minutes of Glory ',
  'The Overtime Enjoyers Club 🍻',
  'Prestigious Tournament of Prestige 🎩',
  'The Ref Forgot To Whistle Cup ',
  'Absolutely Normal Tournament 👍',
  'Spreadsheet Lovers 📊',
  'Historic Event Since Last Week 📖',
  'Draw First Ask 30 Minutes Later',
  'Official Unofficial Hattrick Friendly Challenge',
  'The Weekly Excuse Cup',
  'The Friendly That Isn’t Friendly Cup 😈',
  'The Tournament Formerly Known As Friendly',
  'Divine International',
  'Utopian Cup 🌈',
  'Magical League ⭐️',
  'Magical Beasts and Utopian Draws',
  'The Mythical Championship',
  'Extra-Terrestrial Interstellar 🛸',
  'Titanic Trophy 🚢',
  'The Supernaturals 👻',
  'World Class Championship',
  'The Magnificent Tournament',
  'Stay Brilliant',
  'Winning Is For Losers 💪',
  'Formidable Draw Makers',
  'The Utopian 2 Hours Cup',
  'Inadequate 90 Minutes',
  'Divine Extra 30',
  'Divine Managers Finish Last',
  'Weak 90, Divine 30',
  'Poor 90 Minutes Cup',
  'The Wretched Ones',
  'Disastrous Regulars, Divine Additionals',
  'There and Back Again',
  'The Fellowship of the Draw',
  'One More Turn',
  'The Last Alliance of Midfielders',
  'The Return of the Extra 30',
  'The Two Hour Problem',
  'The Unfinished Match',
  'The Expected Overtime',
  'The League of Extraordinary Draws',
  'The Department of Additional Minutes',
  'The Ministry of Stamina',
  'The Society of Minute Enthusiasts',
  'The Institute of Questionable Tactics',
  'The Academy of Friendly Sciences',
  'The Grand Unified Theory of Draws',
  'The Experimental Physics Invitational',
  'The Schrödinger Result Cup',
  'The Event Horizon League',
  'The Relativity Championship',
  'The Time Dilation Trophy',
  'The Parallel Minutes Cup',
  'Extra Dimensional Minutes Cup',
  'The Statistical Significance Invitational',
  'The Peer Reviewed Tournament',
  'The Scientific Method Cup',
  'The Blame Each Other For Winning Cup',
  'Scream If You Love Draws',
  'The Simulation Of The Extra 30',
  'The 30 Minute League Beta Test Alpha Version',
  'The Final Final Version',
  'The Revised Final Final League Title',
  'The Definitive Edition',
  'The Extended Edition',
  'The Director’s Cut',
  'The Sequel Nobody Asked For',
  'The Third Age Invitational',
  'The Goblet of Extra Time',
  'The Order of the Additional Half Hour',
  'The Chamber of Additional Minutes',
  'The Defence Against Normal Football Cup',
  'Fantastic Draws and Where to Find Them',
  'The League That Must Not End',
  'The Hattricker’s Guide to Extra Time',
  'The Hattricker’s Guide to Extra Time',
  'Harmless Extra 30',
  'Life Begins After 90',
  '42 Minutes Too Short',
  'The Answer Is Additional Minutes',
  'The Resistance Is Futile Cup',
  'The Prime Directive Violation',
  'The Away Team Strikes Back',
  'Return of the Midfield',
  'A New Draw',
  'The Empire Delays Victory',
  'Attack of Extra Minutes',
  'Revenge of the Stamina Coach',
  'The Never Enough Stamina Club',
  'The Multiverse of Match Orders',
  'The Infinite Improbability Cup',
  'The Eternal Regret of Wrong Match Orders',
  'The Last Minute Society',
  'The Divine Brotherhood of Overtime',
  'The Secret Order of Longer Friendlies',
  'The Sacred Extra Thirty',
  'The Cult of Minute 120',
  'The Church of Additional Time',
  'Order of Not Finishing On Time',
  'Art of Not Finishing On Time',
  'Sun Tzus Art of Not Finishing',
  'The Noble Art of Drawing',
  'The Draw Engineering Department',
  'The Department of Competitive Friendship',
  'Committee for Extended Football',
  'The Bureau of Additional Minutes',
  'The Extra Minutes Project',
  'The Great Experiment',
  'The Longest Ninety Minutes',
  'The World Congress of Draws',
  'The International Society of Stamina Abuse',
  'The Magnificent League of Ordinary Managers',
  'The Fellowship of the Extra 30',
  'The Fellowship of the 120 minutes',
  'They Thought We Had Finished',
  'Spreadsheet Replacement Tournament 📊',
  'Friendly Managers Anonymous 🤝',
  'Forum Thread Championship 💬',
  'The Weekly Excuse Cup 📝',
  'Bad Match Orders Invitational 🎮',
  'The Injury Appreciation Society 🩹',
  'The Statistics Enjoyers League 📈',
  'Friends Until Kickoff Cup 😇',
  'The Rivalry Preservation Tournament 🔥',
  'The Beer & Friendlies Cup 🍺',
  'Reasonably Competitive Championship ⚖️',
  'The Casual Grudge Match League 😅',
  'The Screenshot Trophy 🖼️',
  'Managers Making Questionable Decisions Cup 🤔',
  'The Tactical Genius Invitational 🧠',
  'The Community Drama Cup 🎭',
  'The Virtual Grass Classic 🌱',
  'The Midfield Matters League ⚽',
  'The Why Did I Join This Tournament Cup 🤷',
  '120 Minutes of Glory',
  '120 Minutes of Pain',
  'Extra Time Invitational ⌛',
  'Minute Addicts League 🕰️',
  'Overtime Appreciation Society 🤝',
  'The 120 Minute Project 🚀',
  'Give Us More Minutes Cup ⏳',
  'Training Never Sleeps League 😴',
  'Friendly Overtime Championship ⚽',
  'The Stamina Cup 🏃',
  'The Extra 30 Invitational ➕30',
  'Draw First Ask Questions Later Cup 🤔',
  'Operation Minute 120 🎯',
  'The Long Match Society 🕰️',
  'Beyond Minute 90 League 🚦',
  'The Overtime Enjoyers Club 🍻',
  'The Ref Forgot To Whistle Cup 🔔',
  'One More Half Hour Invitational ⏳',
  'The Last 30 Minutes League 📈',
  'Not Finished Yet Cup 🚧',
  '120 Or Bust Championship 💥',
  'Awesome Great Tournament 🤩',
  'Very Serious Tournament 🧐',
  'World Class Invitational 🌍',
  'Magnificent Cup 🏆',
  'Extra-Terrestrial Trophy 👽',
  'The Divine League ✨',
  'Elite Friendly Championship 🏅',
  'The Legendary Cup 📜',
  'Outstanding Invitational ⭐',
  'Absolutely Normal Tournament 👍',
  'Prestigious Tournament of Prestige 🎩',
  'The Tournament Formerly Known As Friendly 🎭',
  'Officially Unofficial Championship 🥇',
  'International Council of Extra Minutes 🌎',
  'Award-Winning Tournament* 🏅',
  'Definitely Not Rigged Cup 🎲',
  "The People's Championship ✊",
  'The Future Hall of Fame Tournament 🏛️',
  'Historic Event Since Last Week 📖',
];
