export const DESCRIPTIONS: string[] = [
  'Winning is weak. Drawing is divine',
  'Points are passable. Extra 30 minutes are titanic',
  'Friendlies are temporary. Screenshots of the standings are forever',
  'Points are temporary. 30 minutes of extra training is eternal',
  'The standings are temporary. Trainings are eternal',
  'Life is short. Matches should be longer',
  'The road to glory is paved with 120-minute drama',
  'The schedule is automatic. The drama is not',
  'Everyone is friendly until the standings are published',
  'Think outside the 90 minutes',
  'The only place where not winning after 90 minutes is a strategic masterclass',
  'Some teams came for fun. Others came to remind everyone who is boss',
  'Some teams dream of victory. Others work hard to not score in regular time',
  'Winning is disastrous. Not scoring is divine',
  "One man's draw is another man's training",
  'Training starts after 90',
  'Created for managers who think 90 minutes is simply inadequate',
  'Join us if you think 90 minutes is simply inadequate',
  'Some teams chase trophies. Others chase that magical extra half-hour',
  'Give your opponent a point and be rewarded with eternity',
  'Where brilliant planning meets disastrous game events',
  'Where divine planning meets idiotic game events',
  'May your form be excellent and your injuries non-existent',
  'May your stamina be supernatural and your midfield weak',
  'May your midfield be poor and your defence divine',
  "Remember: it's only a friendly until you lose",
  "Good luck, have fun, and don't forget to miss your shots",
  'Come for the points. Stay for the extra minutes',
  'Wretched 90 minutes. Utopian 120',
  'What happens in extra time, stays in extra time',
  'The situation has escalated to minute 120',
  'One does not simply finish in 90 minutes',
  'Start slow, finish late',
  "It's not how you start that matters; it's how you don't finish",
  'Start with purpose, finish never',
  'The answer is additional minutes. What was the question?',
  'Winning Is For Losers 💪',
  'Great hattrickers finish last',
  'Legendary hattrickers finish last',
  'Play Weak. Finish Never',
  'Life Begins After 90!',
  'Some minutes are more important than others',
  'Some say a draw, others say glorious victory over time',
  'No pain, no extra minutes',
  'The road to glory is paved with 120-minute draws',
  "You miss 100% of the shots you don't take. So don't take them.",
  'You can now regret setting the wrong match orders for 30 more minutes',
  'See you in the Extra-terrestrial Time',
  'The order of funny match orders',
  'The Ministry Of Silly Match Orders',
  'Every additional minute is a magnificent chance to regret your match orders',
  'Every additional minute is a prolonged chance to regret your match orders',
  'Regret your match orders magnificently',
  'World class ability to not finish on time',
  'Extra-terrestrial opportunity to not finish on time',
  'World class opportunity to regret your match orders for 120 minutes',
  'This tournament is more magnificent than we would have decency to admit',
  'Winning is weak. Drawing is divine',
  'The trophy is solid, but the bragging rights are extra-terrestrial',
  'A tournament so utopian even you signed up',
  'Winners go home. Drawers stay',
  'Give me extra 30 minutes above points any day',
  'Points are passable. Extra 30 minutes are titanic',
  '90 minutes of hard work, 30 minutes of training, a lifetime of regret',
  'The only place where not winning after 90 minutes is a Strategic Masterclass',
  'The only place where not winning after 90 minutes is a Strategic Masterclass',
  'Stamina is just a number until you hit 100+ minutes',
  'Some teams came for fun. Others came to remind everyone who is boss',
  'Friendlies are temporary. Screenshots of standings are forever',
  'Points are temporary. 30 minutes of training is eternal',
  'The standings are temporary. Trainings are eternal',
  'Life is short. Matches should be longer',
  'The road to glory is paved with 120-minute dramas',
  'The road to glory is paved with 120-minute drama',
  'The only tournament where not winning after 90 minutes is a strategic masterclass',
  'A gathering of future champions and current excuses',
  "Keep still and don't move until referee says it's overtime.",
  'Where your score is counted by a magical device on referees left wrist',
  'Everyone is friendly until the standings are published',
  'Winning is excellent. Trash talking is extra-terrestrial',
  'The schedule is automatic. The drama is not',
  'May your players stay healthy and your opponents stay offline',
  'Keep your friends close and your opponents drunk',
  'The road to glory starts with a friendly and ends with statistics',
  "Let's play some imaginary football and judge each other.",
  'Where legends are made and statistics are born',
  'Fight against the match engine',
  'No spreadsheets were harmed in the creation of these tournaments',
  'Mess around, play no pressing and find out',
  'Mess around, win in regular time and find out',
  'Think outside the 90 minutes',
  'Think outside the 90 minutes',
  'Regular time is for regulars. We are not regularing here',
  'The only thing stronger than my team is my false optimism',
  "If your stamina isn't solid, your plans are non-existent.",
  "If you're reading this, you're already behind in the standings.",
  'Play fair, have fun, do not win',
  'Play fair, have fun, go home',
  'The grass is virtual, but the sweat is real',
  'Contains traces of ambition and excessive confidence',
  'So tell me once again how your best player got injured',
  'The standings never lie, but they occasionally enjoy a casual half-truth',
  'Welcome to the tournament where every manager is a tactical genius',
  'Play fair, collect points, drink beer, make friends, win not in time',
  'We are here to declare war versus those who finish on time',
  'Finally an absolutelly normal tournament with no grudges involved',
  'Some teams dream of victory. Others work hard to not score in regular time',
  'The path to greatness begins with clicking "Create Tournament"',
  'The path to greatness begins with clicking "Create Tournament"',
  'Where every minute counts, but some count more than others',
  'Here is to Hattrick, to football, to beer and to 30 extra minutes of all that',
  'Here is to Hattrick, to football, to beer and to 30 extra minutes of all that',
  'Only a few things in life are good enough to keep fighting for extra 30 minutes',
  'Winning is disastrous. Not scoring is divine',
  'Winning is disastrous. Not scoring is divine',
  'May your stamina be supernatural and your midfield weak',
  "One man's draw is another man's training.",
  "One man's draw is another man's training.",
  "The only place that rewards those who can't finish on time.",
  'The only place where you will be rewarded for not finishing on time',
  'The only place where you will be rewarded for not finishing on time',
  'Created for managers who think 90 minutes is simply inadequate',
  'Join us if think 90 minutes is simply inadequate',
  'Why settle for a 90 min drama when you can have 120 minutes of eternal suffering?',
  'A mythical tournament for managers with extra-terrestrial patience',
  'Some teams chase trophies. Others chase that magical extra half-hour',
  'Give your opponent a point and be rewarded with eternity',
  'Where brilliant planning meets disastrous game events',
  'Where divine planning meets idiotic game events',
  'The road to glory is paved with 120-minute draws',
  'May your form be excellent and your injuries non-existent',
  'Training starts after 90',
  'No pressure, just eternal recognition among a very specific group of people',
  'May your midfield be poor and your defence divine',
  'Scientifically optimized extra minutes factory',
  "Remember: it's only a friendly until you lose.",
  'A celebration of football, community, and questionable characters',
  'The finest collection of future champions currently available',
  "Good luck, have fun, and don't forget to miss your shots.",
  'We want some extra',
  'This placeholder description is here because nobody wanted to write a real one',
  'The greatest tournament system in this exact browser tab',
  'The finest collection of minute addicts',
  'The finest collection of minute addicts',
  'Come for the points. Stay for the extra minutes',
  'A tournament so prestigious it already has a premade description',
  'Points are passable. Extra 30 minutes are titanic',
  '90 minutes of hard work, 30 minutes of training, a lifetime of regret',
  'The only tournament where not winning after 90 minutes is a strategic masterclass',
  'Stamina is just a number until you run out of it after 105 mins',
  'Where minutes is not a static number',
  'Where minutes is not just a number',
  'Universe scale opportunity to not finish on time',
  'Make extra minutes not war',
  'No time for winners. We are the drawers 🗄',
  'No time for winners. We are the drawers 🗄',
  'Wretched 90 minutes. Utopian 120',
  'Wretched 90 minutes. Utopian 120',
  'What happens in extra time, stays in extra time',
  'What happens in extra time, stays in extra time',
  'Oops, I Did Extra Time Again',
  'Oops, I Did Extra Time Again',
  'Hit me with that sweet extra time of yours',
  'Hit me with that sweet extra time of yours',
  'This friendly will not escalate quickly',
  'This friendly will not escalate quickly',
  'This match could have been an email',
  'This match could have been an email',
  'The situation has escalated to minute 120',
  'The situation has escalated to minute 120',
  'One does not simply finish in 90 minutes',
  'One does not simply finish in 90 minutes',
  'Start slow, finish late',
  "It's not how you start that matters; it's how you don't finish.",
  'Start with purpose, finish never',
  'The answer is additional minutes. What was the question?',
  'The answer is additional minutes. What was the question?',
  'Gentlemen prefer longer minutes',
  'And how long can YOU last?',
  'Winning Is For Losers 💪',
  'Always look on the extra side of time',
  'Always look on the extra side of time',
  'Bloody battles to life and death formerly known as friendlies',
  'Terrifying battles to life and death formerly known as friendlies',
  'Great hattrickers finish last',
  'Legendary hattrickers finish last',
  'The Ministry Of Silly Match Orders',
  'The Ministry Of Silly Match Orders',
  'DRAW ME like one of your international friendlies',
  'DRAW ME like one of your international friendlies',
  'Make Extra Minutes Not War',
  'Weak 90 Minutes Cup',
  'Play Weak. Finish Never',
  'I will love you till the end of regular time 💕',
  'I will love you till the end of regular time 💕',
  'The Fellowship of the Draw',
  'Somebody Flew Over The Extra Time',
  'Rage Against The Final Whistle',
  'Rage Against The Final Whistle',
  'The Institute of Questionable Tactics',
  'Utopian Managers Finish Last',
  'Play Weak. Finish Never',
  'See You At The End Of Overtime',
  'Till overtime sets us apart..',
  'Friendlies: Extended, Uncut, Unrated',
  'The Secret Chamber of Additional Minutes',
  'Fantastic Draws and Where to Find Them',
  'The Hattricker’s Guide to Overtime',
  'The Hattricker’s Guide to Overtime',
  'Life Begins After 90!',
  'Still Training After 90?',
  'Still Training After 90?',
  'Some minutes are more important than others',
  'Some minutes are bigger than other minutes',
  'Some say a draw, others say - glorious victory over time!',
  'Some say a draw, others say - glorious victory over time!',
  'The 120 Minute Drama Club',
  'The 120 Min Regret of Wrong Match Orders',
  'The Extended Regret of Wrong Match Orders',
  'Committee for Extended Football',
  'The Bureau of Additional Minutes',
  'The Spreadsheet Retirement Club',
  'No country for 90 minutes',
  'Start Slow, Finish Late',
  'No pain, no extra minutes',
  'Oh No I Scored Again',
  'The Timekeepers Society',
  'Once Upon An Overtime',
  'Once Upon An Overtime',
  'Extra time never happens to me',
  "And I can't live... With or without extra minutes.",
  'Do you really want to play forever?',
  'MOGA - Make Overtime Great Again',
  'Oops, I Did Overtime Again',
  'Oops, I Did Overtime Again',
  'One Does Not Simply Finish In 90 Minutes',
  'One Does Not Simply Finish In 90 Minutes',
  "I don't always make it to 120 mins, but when I do... half my squad gets hospitalized.",
  'We feed on extra minutes',
  'Why settle for 90 min drama when you can have 120+ mins of that?',
  'Why settle for 90 min drama when you can have 120+ mins?',
  'I know what you did overtime',
  'The dark side of the extra time',
  'Everybody bites the extra time',
  'Burning the midnight minutes',
  'Burning the extra minutes',
  'No eternal reward will forgive us now for wasting the overtime',
  'Where Extra Minutes Happen',
  'Got some more of those... minutes?',
  "Sun Tzu's Art of Not Finishing In Time",
  'Somebody Flew Over The Regular Time Report',
  'No Referee, Our Goal Should Not Have Count',
  "You miss 100% of the shots you don't take. So don't take them.",
  'Shiny happy extra minutes holding hands',
  'Smells like team spirit',
  "Don't cry for me regular time...",
  'You can now regret setting the wrong match orders for 30 more mins!',
  'The road to hell is paved with winning 120 min battles in regular time',
  'See you in the Extra-terrestrial Time',
  'The order of tactical disgrace',
  'Want to confuse your date? Ask them out for 120 minutes',
  "I'd date you for 120 minutes any day",
  '120 minutes this wednesday? Sounds like a date to me',
  'Rage Against the Match Engine',
];

export const EXTRA_TIME_TOURNAMENT_NAMES = [
  'The Divine Draw Invitational',
  'The Magnificent Additional Minutes',
  'The Utopian Overtime Society',
  'The Extra-Terrestrial Time League',
  'The Mythical 120th Minute',
  'The Titanic Training Opportunity',
  'The Supernatural Stamina Cup',
  'The Outstanding Overtime Championship',
  'The Brilliant Draw Association',
  'The Formidable Extra Half Hour',
  'The Excellent Overtime Invitational',
  'The Solid Stamina Society',
  'The Passable Victory Resistance',
  'The Inadequate Ninety Minutes',
  'The Weak Final Whistle',
  'The Poor Finishing Department',
  'The Wretched Ninety Minutes',
  'Rage Against the Final Whistle',
  'The Disastrous Regular Time League',
  'The Non-Existent End Of Match',
  'The Last Thirty Minutes',
  'The Path To Minute 120',
  'The Brotherhood Of Overtime',
  'The Church Of Additional Minutes',
  'The Cult Of The 120th Minute',
  'The Order Of Not Finishing On Time',
  'The Resistance To Regular Time',
  'The Final Whistle Resistance',
  'Life Begins After 90',
  'The League Beyond Ninety',
  'One Does Not Simply Finish In 90 Minutes',
  'The Match That Would Not End',
  'The Refusal To Finish Cup',
  'The Unexpected Overtime',
  'The Expected Overtime',
  'The Additional Additional Time Cup',
  'The Third Period Club',
  'The Third Period Invitational',
  'The Longest Ninety Minutes',
  'The Situation Has Escalated To Minute 120',
  'The Last Thing Stamina Sees',
  'Back For Thirty More',
  'Still Not Finished',
  'Oops, We Need 30 More Minutes',
  'Oops, I Did Extra Time Again',
  'Extra Time And Other Bad Decisions',
  'The Fine, We’ll Do 120 Cup',
  'The Cult Of The Draw',
  'The Fellowship Of The Draw',
  'The Brotherhood Of Additional Minutes',
  'The Return Of The Extra 30',
  'Attack Of Extra Minutes',
  'The Expected Thirty',
  'My Sweet 120th',
  'May Contain Additional Minutes',
  'Nobody Expected Extra Time',
  'The Two Hour Problem',
  'The Unfinished Match',
  'The Answer Is Additional Minutes',
  'The Art Of Not Finishing On Time',
  'The Additional Time Authority',
  'The Office Of Overtime Affairs',
  'Committee For Extended Football',
  'The Bureau Of Additional Minutes',
  'The Overtime Preservation Society',
  'The Extra Minutes Project',
  'The Time Bending Society',
  'The League That Must Not End',
  'The Extra-Terrestrial Time Cup',
  'The Unexpected Thirty Minutes',
  'Remain Calm Before 90',
  'The Last Stand Of Regular Time',
  'The Death Of The Final Whistle',
  'Ninety Minutes Was Not Enough',
  'Just A Few Minutes More',
  'One More Minute Baby',
  'Hit Me With Your Extra Time',
  'The Delirious, the Satisfied and the Content',
  'High On Life Invitational',
  'The Murderous, the Furious and the Irritated',
];

export const UNIVERSAL_TOURNAMENT_NAMES = [
  'We Are Calm, Content and Satisfied',
  'The Murderous Sponsors Invitational',
  'The Murderous Sponsors Invitational',
  'Delirious Fans and Sponsors Cup',
  'Delirious Fans and Satisfied Sponsors Cup',
  'The Sponsors Are Dancing',
  'Dancing In The Streats Cup',
  'Sponsors Dancing In The Streets',
  'The Sponsors Are Sending Love Poems Cup',
  'Sponsors Sending Love Poems Cup',
  'The Dancing In The Streets Cup',
  'The Sending Love Poems Cup',
  'Love Poems From Fans',
  'High On Life Invitational',
  'The Delirious, the Satisfied and the Content',
  'The Murderous, the Furious and the Irritated',
  "Let's Humiliate Them",
  'We Are Calm, Content and Satisfied',
  'The Calm Sponsors Invitational',
  'The Furious Sponsors Cup',
  'Outstanding Expectations',
  'Composed Spirit International',
  'Walking on Clouds Universal',
  'Piece Of Cake Invitational',
  'Least Important Cup in the Universe',
  'Slightly Exaggerated Universal',
  'The Righteous and The Upright',
  'The Infamous, The Nasty & The Unstable',
  'The Calm, The Upright and The Pleasant',
  'We Have The Edge Trophy',
  'They Have The Edge Trophy',
  'The Weak and the Inferior',
  'Every Day in This Tournament is a Bonus',
  'Aim For The Title!',
  'Piece of Cake!',
  'It Will Be a Close Affair',
  'The Close Affair Cup',
  'We Are Favourites League',
  'We Will Lose Invitational',
  'We Are Outclassed Championship',
  'Better Not Show Up Tournament',
  'Better Not Show Up Cup',
  'The Eternal Regret Of Wrong Match Orders',
  'The Utopian Regret Of Wrong Match Orders',
  'The Magnificent Stamina League',
  'The Divine Draw Invitational',
  'The Mythical Midfield Trophy',
  'The Titanic Training Tournament',
  'The Formidable Friendly League',
  'The Brilliant Draw Championship',
  'The Outstanding Stamina Society',
  'The World Class Training Cup',
  'The Excellent Midfield Association',
  'The Solid Form Invitational',
  'The Passable Victory Cup',
  'The Weak Victory League',
  'The Poor Finishing Society',
  'The Wretched Winners Club',
  'The Disastrous Ninety Minutes',
  'The Non-Existent Finishing School',
  'The Sponsors Are Delirious Cup',
  'The Sponsors Are Sending Love Poems Cup',
  'The Sponsors Are Dancing In The Streets Cup',
  'The Fans Are Delirious League',
  'The Fans Are Furious Invitational',
  'The Fans Are Murderous Cup',
  'The Piece Of Cake Invitational',
  'The Better Not Show Up Cup',
  'We Have The Edge Trophy',
  'The We Will Lose Invitational',
  'The We Are Favourites Cup',
  'The Close Affair Championship',
  'The Department Of Match Orders',
  'The Ministry Of Silly Match Orders',
  'The Institute Of Questionable Tactics',
  'The Match Order Support Group',
  'The Match Order Archaeology Society',
  'Please Explain This Match Rating',
  'One More Match Engine Miracle',
  'The Midfield Preservation Society',
  'The Form Recovery Invitational',
  'The Draw Engineering Department',
  'The Bureau Of Draw Enforcement',
  'The Department Of Competitive Friendship',
  'The Academy Of Competitive Friendship',
  'The Society Of Perpetual Draws',
  'The Last Friendly You Will Take Personally',
  'The Weekly Stamina Inspection',
  'The Weekly Celebration Of Stamina',
  'The Training Comes First League',
  'The Match Rating Appreciation Society',
  'The Spreadsheet Retirement Fund',
  'The Spreadsheet Replacement Tournament',
  'The Great Experiment',
  'The Strategic Draw Invitational',
  'The Department Of Draw Affairs',
  'The Timekeepers Society',
  'The Noble Art Of Drawing',
  'The Delayed Victory League',
  'The Calm Before Kickoff',
  'The Delirious Managers Association',
  'The Furious Supporters Club',
  'The Murderous Expectations Cup',
  'The Utopian Managers Society',
  'The Divine Training Department',
  'The Mythical Match Orders League',
  'The Brilliant Midfield Club',
  'The Formidable Form Cup',
  'The Outstanding Opportunity League',
  'The Excellent Excuses Association',
  'The Solid Performance Society',
  'The Passable Results Federation',
  'The Weak Victory Preservation Society',
  'The Poor Finishing Invitational',
  'The Wretched Ninety Minutes',
  'The Disastrous Winners Circle',
  'The Non-Existent Defence League',
  'Play Weak. Finish Never',
  'Start Slow, Finish Late',
  'Friends Until Kickoff',
  'Winning Is For Losers',
  'One Point Is Plenty',
  'Yet Another Draw Club',
  'Oops, Still 0–0',
  'Oops, Another Draw',
  'The Beer Before Analysis Club',
  'The Next Morning Excuse League',
  'The Accidental Masterpiece',
  'The Highly Questionable Invitational',
  'The Dead Friendlies Society',
  'Friendly Fire',
  'Professional Time Wasters',
  'Task Failed Successfully',
  'Working As Intended',
  'This tournament is a bug',
  'Bots of the world, unite!',
  'Unexpected Behaviour',
  'Remember When This Match Started?',
  'Half My Squad Got Injured But I Did It',
  'The Most Important Tournament Today',
  'Prestigious Tournament Of Prestige',
  'Absolutely Normal Tournament',
  'Historic Event Since Last Week',
];

export const TOURNAMENT_DEFAULT_120MIN = [
  'Winning is weak. Drawing is divine',
  'Points are passable. Extra 30 minutes are titanic',
  'Life is short. Matches should be longer',
  'Think outside the 90 minutes',
  'Training starts after 90',
  'Come for the points. Stay for the extra minutes',
  'Wretched 90 minutes. Utopian 120',
  'One does not simply finish in 90 minutes',
  'Life Begins After 90!',
  'The Fellowship Of The Draw',
  'Friendlies are temporary. Screenshots of standings are forever',
  'The schedule is automatic. The drama is not',
  'Everyone is friendly until the standings are published',
  "One man's draw is another man's training",
  'Give your opponent a point and be rewarded with eternity',
  'What happens in extra time, stays in extra time',
  'Start slow, finish late',
  'The answer is additional minutes. What was the question?',
  'Some minutes are more important than others',
  'The Ministry Of Silly Match Orders',
];

export const TOURNAMENT_DEFAULT = [
  "One man's draw is another one's training",
  'United by football, divided by ambition',
  'United by Hattrick, separated by the standings',
  'May only goal difference separate us',
  'Where strangers meet and rivals are born',
  'Bound by football, united by incorrect statistics',
  'Different places, different clubs, same addiction',
  'Where football brings us together and competition does the rest',
  'Where great challenges are met and greater excuses are born',
  'A gathering of managers, optimists and a ton of future excuses',
  'Where football, statistics and good vibes occasionally coexist',
  'Temporarily united against the match engine',
  'For every manager is a genius, the match engine must silently remain wrong',
  'Where brilliant planning meets dumb match events',
  'Built on football, spreadsheets and false optimism',
  'Where football meets spreadsheets and somehow becomes a sport',
  "Here's to the beautiful game, managed one mistake at a time",
  'May only the goal difference separate us',
  'Where every result creates a new theory',
  "Here's to the beautiful game, managed one mistake at a time",
  'It\'s really a "friendly" only until the kickoff',
  'Serious enough to care, friendly enough to laugh uncontrollably',
  'Where respect is earned and banter is inevitable',
  'The standings matter. The people matter more',
  'Every season starts with hope and ends with a drink',
  'Some chase trophies. Others chase those who chase trophies.',
  'May the best plans somehow find a way to survive',
  'Another season, another chance to plan it all wrong',
  'Built by managers, maintained by stubbornness',
  'Different teams but shared delusions of tactical brilliance',
  'United by football, statistics and questionable decisions',
  'Where optimism has to survive contact with reality every week',
  'Built on friendship, competition and selective memory',
  'Every manager arrives with a plan and leaves with a theory',
  'Where great mistakes are made from week to week',
  'Friendlies are temporary. Screenshots of standings are forever',
  'The schedule is automatic. The drama is not',
  'Where legends are made out of nothing but statistics',
  'The standings never lie, but they occasionally enjoy a casual half-truth',
  'Welcome to the tournament where every manager is a tactical genius',
  'The road to glory starts with a friendly and ends with statistics',
  'Contains traces of ambition and excessive confidence',
  'The only thing stronger than my team is my false optimism',
  'The grass might be virtual, but the sweat is real',
  'No spreadsheets were harmed in the creation of this tournament',
  'Where every minute counts, but some count more than others',
  'Play fair, collect points, drink beer, make friends',
  'A celebration of football, community and questionable characters',
  'The finest collection of future champions currently available',
  'Where legends are made and excuses are perfected',
];

export const TOURNAMENT_NAMES = [...EXTRA_TIME_TOURNAMENT_NAMES, ...UNIVERSAL_TOURNAMENT_NAMES];
