// Generated from src/utils/worlddetails.xml (CHPP worldDetails v1.2).
// LeagueID and CountryID are separate namespaces; special leagues have no country.
export interface HattrickWorldLeague {
  leagueId: number;
  leagueName?: string;
  englishName?: string;
  countryId: number | null;
  countryName: string | null;
}

export const HATTRICK_WORLD_DETAILS: Record<number, HattrickWorldLeague> = {
  1: {"leagueId":1,"leagueName":"Svezia","englishName":"Sweden","countryId":1,"countryName":"Sverige"},
  2: {"leagueId":2,"leagueName":"Inghilterra","englishName":"England","countryId":2,"countryName":"England"},
  3: {"leagueId":3,"leagueName":"Germania","englishName":"Germany","countryId":3,"countryName":"Deutschland"},
  4: {"leagueId":4,"leagueName":"Italia","englishName":"Italy","countryId":4,"countryName":"Italia"},
  5: {"leagueId":5,"leagueName":"Francia","englishName":"France","countryId":5,"countryName":"France"},
  6: {"leagueId":6,"leagueName":"Messico","englishName":"Mexico","countryId":6,"countryName":"México"},
  7: {"leagueId":7,"leagueName":"Argentina","englishName":"Argentina","countryId":7,"countryName":"Argentina"},
  8: {"leagueId":8,"leagueName":"Stati Uniti d'America","englishName":"USA","countryId":8,"countryName":"USA"},
  9: {"leagueId":9,"leagueName":"Norvegia","englishName":"Norway","countryId":9,"countryName":"Norge"},
  11: {"leagueId":11,"leagueName":"Danimarca","englishName":"Denmark","countryId":10,"countryName":"Danmark"},
  12: {"leagueId":12,"leagueName":"Finlandia","englishName":"Finland","countryId":11,"countryName":"Suomi"},
  14: {"leagueId":14,"leagueName":"Paesi Bassi","englishName":"Netherlands","countryId":12,"countryName":"Nederland"},
  15: {"leagueId":15,"leagueName":"Oceania","englishName":"Oceania","countryId":13,"countryName":"Oceania"},
  16: {"leagueId":16,"leagueName":"Brasile","englishName":"Brazil","countryId":22,"countryName":"Brasil"},
  17: {"leagueId":17,"leagueName":"Canada","englishName":"Canada","countryId":14,"countryName":"Canada"},
  18: {"leagueId":18,"leagueName":"Cile","englishName":"Chile","countryId":17,"countryName":"Chile"},
  19: {"leagueId":19,"leagueName":"Colombia","englishName":"Colombia","countryId":18,"countryName":"Colombia"},
  20: {"leagueId":20,"leagueName":"India","englishName":"India","countryId":27,"countryName":"India"},
  21: {"leagueId":21,"leagueName":"Irlanda","englishName":"Ireland","countryId":16,"countryName":"Ireland"},
  22: {"leagueId":22,"leagueName":"Giappone","englishName":"Japan","countryId":25,"countryName":"Nippon"},
  23: {"leagueId":23,"leagueName":"Perù","englishName":"Peru","countryId":21,"countryName":"Perú"},
  24: {"leagueId":24,"leagueName":"Polonia","englishName":"Poland","countryId":26,"countryName":"Polska"},
  25: {"leagueId":25,"leagueName":"Portogallo","englishName":"Portugal","countryId":23,"countryName":"Portugal"},
  26: {"leagueId":26,"leagueName":"Scozia","englishName":"Scotland","countryId":15,"countryName":"Scotland"},
  27: {"leagueId":27,"leagueName":"Sudafrica","englishName":"South Africa","countryId":24,"countryName":"South Africa"},
  28: {"leagueId":28,"leagueName":"Uruguay","englishName":"Uruguay","countryId":19,"countryName":"Uruguay"},
  29: {"leagueId":29,"leagueName":"Venezuela","englishName":"Venezuela","countryId":20,"countryName":"Venezuela"},
  30: {"leagueId":30,"leagueName":"Corea del Sud","englishName":"South Korea","countryId":29,"countryName":"Hanguk"},
  31: {"leagueId":31,"leagueName":"Thailandia","englishName":"Thailand","countryId":30,"countryName":"Prathet Thai"},
  32: {"leagueId":32,"leagueName":"Turchia","englishName":"Turkey","countryId":31,"countryName":"Türkiye"},
  33: {"leagueId":33,"leagueName":"Egitto","englishName":"Egypt","countryId":32,"countryName":"Misr"},
  34: {"leagueId":34,"leagueName":"Repubblica Popolare Cinese","englishName":"People's Republic of China","countryId":28,"countryName":"China"},
  35: {"leagueId":35,"leagueName":"Russia","englishName":"Russia","countryId":34,"countryName":"Rossiya"},
  36: {"leagueId":36,"leagueName":"Spagna","englishName":"Spain","countryId":35,"countryName":"España"},
  37: {"leagueId":37,"leagueName":"Romania","englishName":"Romania","countryId":36,"countryName":"România"},
  38: {"leagueId":38,"leagueName":"Islanda","englishName":"Iceland","countryId":37,"countryName":"Ísland"},
  39: {"leagueId":39,"leagueName":"Austria","englishName":"Austria","countryId":33,"countryName":"Österreich"},
  44: {"leagueId":44,"leagueName":"Belgio","englishName":"Belgium","countryId":38,"countryName":"Belgium"},
  45: {"leagueId":45,"leagueName":"Malesia","englishName":"Malaysia","countryId":39,"countryName":"Malaysia"},
  46: {"leagueId":46,"leagueName":"Svizzera","englishName":"Switzerland","countryId":40,"countryName":"Schweiz"},
  47: {"leagueId":47,"leagueName":"Singapore","englishName":"Singapore","countryId":41,"countryName":"Singapore"},
  50: {"leagueId":50,"leagueName":"Grecia","englishName":"Greece","countryId":45,"countryName":"Hellas"},
  51: {"leagueId":51,"leagueName":"Ungheria","englishName":"Hungary","countryId":44,"countryName":"Magyarország"},
  52: {"leagueId":52,"leagueName":"Repubblica Ceca","englishName":"Czechia","countryId":46,"countryName":"Česko"},
  53: {"leagueId":53,"leagueName":"Lettonia","englishName":"Latvia","countryId":48,"countryName":"Latvija"},
  54: {"leagueId":54,"leagueName":"Indonesia","englishName":"Indonesia","countryId":49,"countryName":"Indonesia"},
  55: {"leagueId":55,"leagueName":"Filippine","englishName":"Philippines","countryId":50,"countryName":"Pilipinas"},
  56: {"leagueId":56,"leagueName":"Estonia","englishName":"Estonia","countryId":47,"countryName":"Eesti"},
  57: {"leagueId":57,"leagueName":"Serbia","englishName":"Serbia","countryId":43,"countryName":"Srbija"},
  58: {"leagueId":58,"leagueName":"Croazia","englishName":"Croatia","countryId":42,"countryName":"Hrvatska"},
  59: {"leagueId":59,"leagueName":"Hong Kong (RPC)","englishName":"Hong Kong","countryId":53,"countryName":"Hong Kong, China"},
  60: {"leagueId":60,"leagueName":"Taiwan","englishName":"Chinese Taipei","countryId":52,"countryName":"Chinese Taipei"},
  61: {"leagueId":61,"leagueName":"Galles","englishName":"Wales","countryId":56,"countryName":"Cymru"},
  62: {"leagueId":62,"leagueName":"Bulgaria","englishName":"Bulgaria","countryId":55,"countryName":"Bulgaria"},
  63: {"leagueId":63,"leagueName":"Israele","englishName":"Israel","countryId":51,"countryName":"Israel"},
  64: {"leagueId":64,"leagueName":"Slovenia","englishName":"Slovenia","countryId":57,"countryName":"Slovenija"},
  66: {"leagueId":66,"leagueName":"Lituania","englishName":"Lithuania","countryId":61,"countryName":"Lietuva"},
  67: {"leagueId":67,"leagueName":"Slovacchia","englishName":"Slovakia","countryId":66,"countryName":"Slovensko"},
  68: {"leagueId":68,"leagueName":"Ucraina","englishName":"Ukraine","countryId":62,"countryName":"Ukraina"},
  69: {"leagueId":69,"leagueName":"Bosnia ed Erzegovina","englishName":"Bosnia and Herzegovina","countryId":63,"countryName":"Bosna i Hercegovina"},
  70: {"leagueId":70,"leagueName":"Vietnam","englishName":"Vietnam","countryId":65,"countryName":"Việt Nam"},
  71: {"leagueId":71,"leagueName":"Pakistan","englishName":"Pakistan","countryId":64,"countryName":"Pakistan"},
  72: {"leagueId":72,"leagueName":"Paraguay","englishName":"Paraguay","countryId":67,"countryName":"Paraguay"},
  73: {"leagueId":73,"leagueName":"Ecuador","englishName":"Ecuador","countryId":68,"countryName":"Ecuador"},
  74: {"leagueId":74,"leagueName":"Bolivia","englishName":"Bolivia","countryId":69,"countryName":"Bolivia"},
  75: {"leagueId":75,"leagueName":"Nigeria","englishName":"Nigeria","countryId":70,"countryName":"Nigeria"},
  76: {"leagueId":76,"leagueName":"Isole Faroe","englishName":"Faroe Islands","countryId":71,"countryName":"Føroyar"},
  77: {"leagueId":77,"leagueName":"Marocco","englishName":"Morocco","countryId":72,"countryName":"Al Maghrib"},
  79: {"leagueId":79,"leagueName":"Arabia Saudita","englishName":"Saudi Arabia","countryId":75,"countryName":"Saudi Arabia"},
  80: {"leagueId":80,"leagueName":"Tunisia","englishName":"Tunisia","countryId":76,"countryName":"Tounes"},
  81: {"leagueId":81,"leagueName":"Costa Rica","englishName":"Costa Rica","countryId":77,"countryName":"Costa Rica"},
  83: {"leagueId":83,"leagueName":"Emirati Arabi Uniti","englishName":"United Arab Emirates","countryId":78,"countryName":"United Arab Emirates"},
  84: {"leagueId":84,"leagueName":"Lussemburgo","englishName":"Luxembourg","countryId":79,"countryName":"Lëtzebuerg"},
  85: {"leagueId":85,"leagueName":"Iran","englishName":"Iran","countryId":80,"countryName":"Iran"},
  88: {"leagueId":88,"leagueName":"Repubblica Dominicana","englishName":"Dominican Republic","countryId":83,"countryName":"República Dominicana"},
  89: {"leagueId":89,"leagueName":"Cipro","englishName":"Cyprus","countryId":82,"countryName":"Cyprus"},
  91: {"leagueId":91,"leagueName":"Bielorussia","englishName":"Belarus","countryId":87,"countryName":"Belarus"},
  93: {"leagueId":93,"leagueName":"Irlanda del Nord","englishName":"Northern Ireland","countryId":88,"countryName":"Northern Ireland"},
  94: {"leagueId":94,"leagueName":"Giamaica","englishName":"Jamaica","countryId":89,"countryName":"Jamaica"},
  95: {"leagueId":95,"leagueName":"Kenya","englishName":"Kenya","countryId":90,"countryName":"Kenya"},
  96: {"leagueId":96,"leagueName":"Panama","englishName":"Panama","countryId":91,"countryName":"Panamá"},
  97: {"leagueId":97,"leagueName":"Macedonia del Nord","englishName":"North Macedonia","countryId":92,"countryName":"Severna Makedonija"},
  98: {"leagueId":98,"leagueName":"Albania","englishName":"Albania","countryId":94,"countryName":"Shqipëria"},
  99: {"leagueId":99,"leagueName":"Honduras","englishName":"Honduras","countryId":95,"countryName":"Honduras"},
  100: {"leagueId":100,"leagueName":"El Salvador","englishName":"El Salvador","countryId":96,"countryName":"El Salvador"},
  101: {"leagueId":101,"leagueName":"Malta","englishName":"Malta","countryId":97,"countryName":"Malta"},
  102: {"leagueId":102,"leagueName":"Kirghizistan","englishName":"Kyrgyz Republic","countryId":98,"countryName":"Kyrgyz Republic"},
  103: {"leagueId":103,"leagueName":"Moldavia","englishName":"Moldova","countryId":99,"countryName":"Moldova"},
  104: {"leagueId":104,"leagueName":"Georgia","englishName":"Georgia","countryId":100,"countryName":"Sakartvelo"},
  105: {"leagueId":105,"leagueName":"Andorra","englishName":"Andorra","countryId":101,"countryName":"Andorra"},
  106: {"leagueId":106,"leagueName":"Giordania","englishName":"Jordan","countryId":103,"countryName":"Al Urdun"},
  107: {"leagueId":107,"leagueName":"Guatemala","englishName":"Guatemala","countryId":102,"countryName":"Guatemala"},
  110: {"leagueId":110,"leagueName":"Trinidad e Tobago","englishName":"Trinidad & Tobago","countryId":105,"countryName":"Trinidad & Tobago"},
  111: {"leagueId":111,"leagueName":"Nicaragua","englishName":"Nicaragua","countryId":121,"countryName":"Nicaragua"},
  112: {"leagueId":112,"leagueName":"Kazakistan","englishName":"Kazakhstan","countryId":122,"countryName":"Kazakhstan"},
  113: {"leagueId":113,"leagueName":"Suriname","englishName":"Suriname","countryId":123,"countryName":"Suriname"},
  117: {"leagueId":117,"leagueName":"Liechtenstein","englishName":"Liechtenstein","countryId":125,"countryName":"Liechtenstein"},
  118: {"leagueId":118,"leagueName":"Algeria","englishName":"Algeria","countryId":126,"countryName":"Algérie"},
  119: {"leagueId":119,"leagueName":"Mongolia","englishName":"Mongolia","countryId":127,"countryName":"Mongol Uls"},
  120: {"leagueId":120,"leagueName":"Libano","englishName":"Lebanon","countryId":128,"countryName":"Lebanon"},
  121: {"leagueId":121,"leagueName":"Senegal","englishName":"Senegal","countryId":86,"countryName":"Sénégal"},
  122: {"leagueId":122,"leagueName":"Armenia","englishName":"Armenia","countryId":104,"countryName":"Armenia"},
  123: {"leagueId":123,"leagueName":"Bahrein","englishName":"Bahrain","countryId":129,"countryName":"Bahrain"},
  124: {"leagueId":124,"leagueName":"Barbados","englishName":"Barbados","countryId":130,"countryName":"Barbados"},
  125: {"leagueId":125,"leagueName":"Capo Verde","englishName":"Cape Verde","countryId":131,"countryName":"Cabo Verde"},
  126: {"leagueId":126,"leagueName":"Costa d’Avorio","englishName":"Côte d’Ivoire","countryId":132,"countryName":"Côte d’Ivoire"},
  127: {"leagueId":127,"leagueName":"Kuwait","englishName":"Kuwait","countryId":134,"countryName":"Al Kuwayt"},
  128: {"leagueId":128,"leagueName":"Iraq","englishName":"Iraq","countryId":135,"countryName":"Al Iraq"},
  129: {"leagueId":129,"leagueName":"Azerbaigian","englishName":"Azerbaijan","countryId":133,"countryName":"Azərbaycan"},
  130: {"leagueId":130,"leagueName":"Angola","englishName":"Angola","countryId":137,"countryName":"Angola"},
  131: {"leagueId":131,"leagueName":"Montenegro","englishName":"Montenegro","countryId":136,"countryName":"Crna Gora"},
  132: {"leagueId":132,"leagueName":"Bangladesh","englishName":"Bangladesh","countryId":138,"countryName":"Bangladesh"},
  133: {"leagueId":133,"leagueName":"Yemen","englishName":"Yemen","countryId":139,"countryName":"Al Yaman"},
  134: {"leagueId":134,"leagueName":"Oman","englishName":"Oman","countryId":140,"countryName":"Oman"},
  135: {"leagueId":135,"leagueName":"Mozambico","englishName":"Mozambique","countryId":142,"countryName":"Moçambique"},
  136: {"leagueId":136,"leagueName":"Brunei","englishName":"Brunei","countryId":143,"countryName":"Brunei"},
  137: {"leagueId":137,"leagueName":"Ghana","englishName":"Ghana","countryId":144,"countryName":"Ghana"},
  138: {"leagueId":138,"leagueName":"Cambogia","englishName":"Cambodia","countryId":145,"countryName":"Kampuchea"},
  139: {"leagueId":139,"leagueName":"Benin","englishName":"Benin","countryId":147,"countryName":"Benin"},
  140: {"leagueId":140,"leagueName":"Siria","englishName":"Syria","countryId":148,"countryName":"Suriyah"},
  141: {"leagueId":141,"leagueName":"Qatar","englishName":"Qatar","countryId":149,"countryName":"Qatar"},
  142: {"leagueId":142,"leagueName":"Tanzania","englishName":"Tanzania","countryId":150,"countryName":"Tanzania"},
  143: {"leagueId":143,"leagueName":"Uganda","englishName":"Uganda","countryId":153,"countryName":"Uganda"},
  144: {"leagueId":144,"leagueName":"Maldive","englishName":"Maldives","countryId":154,"countryName":"Dhivehi Raajje"},
  145: {"leagueId":145,"leagueName":"Uzbekistan","englishName":"Uzbekistan","countryId":163,"countryName":"Uzbekistan"},
  146: {"leagueId":146,"leagueName":"Camerun","englishName":"Cameroon","countryId":165,"countryName":"Cameroon"},
  147: {"leagueId":147,"leagueName":"Cuba","englishName":"Cuba","countryId":93,"countryName":"Cuba"},
  148: {"leagueId":148,"leagueName":"Palestina","englishName":"Palestine","countryId":166,"countryName":"Palestine"},
  149: {"leagueId":149,"leagueName":"São Tomé e Príncipe","englishName":"São Tomé e Príncipe","countryId":177,"countryName":"São Tomé e Príncipe"},
  151: {"leagueId":151,"leagueName":"Comore","englishName":"Comoros","countryId":180,"countryName":"Comoros"},
  152: {"leagueId":152,"leagueName":"Sri Lanka","englishName":"Sri Lanka","countryId":175,"countryName":"Sri Lanka"},
  153: {"leagueId":153,"leagueName":"Curaçao","englishName":"Curaçao","countryId":178,"countryName":"Curaçao"},
  154: {"leagueId":154,"leagueName":"Guam","englishName":"Guam","countryId":179,"countryName":"Guam"},
  155: {"leagueId":155,"leagueName":"Repubblica Democratica del Congo","englishName":"Democratic Republic of the Congo","countryId":181,"countryName":"DR Congo"},
  156: {"leagueId":156,"leagueName":"Etiopia","englishName":"Federal Democratic Republic of Ethiopia","countryId":182,"countryName":"Ethiopia"},
  157: {"leagueId":157,"leagueName":"Saint Vincent e Grenadine","englishName":"Saint Vincent and the Grenadines","countryId":184,"countryName":"Saint Vincent and the Grenadines"},
  158: {"leagueId":158,"leagueName":"Belize","englishName":"Belize","countryId":186,"countryName":"Belize"},
  159: {"leagueId":159,"leagueName":"Madagascar","englishName":"Madagascar","countryId":183,"countryName":"Madagascar"},
  160: {"leagueId":160,"leagueName":"Botswana","englishName":"Botswana","countryId":185,"countryName":"Botswana"},
  161: {"leagueId":161,"leagueName":"Birmania","englishName":"Myanmar","countryId":189,"countryName":"Myanmar"},
  162: {"leagueId":162,"leagueName":"Zambia","englishName":"Zambia","countryId":187,"countryName":"Zambia"},
  163: {"leagueId":163,"leagueName":"San Marino","englishName":"San Marino","countryId":191,"countryName":"San Marino"},
  164: {"leagueId":164,"leagueName":"Haiti","englishName":"Haiti","countryId":188,"countryName":"Haiti"},
  165: {"leagueId":165,"leagueName":"Porto Rico","englishName":"Puerto Rico","countryId":190,"countryName":"Puerto Rico"},
  166: {"leagueId":166,"leagueName":"Grenada","englishName":"Grenada","countryId":194,"countryName":"Grenada"},
  167: {"leagueId":167,"leagueName":"Burkina Faso","englishName":"Burkina Faso","countryId":193,"countryName":"Burkina Faso"},
  168: {"leagueId":168,"leagueName":"Nepal","englishName":"Nepal","countryId":192,"countryName":"Nepal"},
  169: {"leagueId":169,"leagueName":"Guyana","englishName":"Guyana","countryId":197,"countryName":"Guyana"},
  170: {"leagueId":170,"leagueName":"Tahiti","englishName":"Tahiti","countryId":196,"countryName":"Tahiti"},
  171: {"leagueId":171,"leagueName":"Guinea","englishName":"Guinea","countryId":198,"countryName":"Guinea"},
  172: {"leagueId":172,"leagueName":"Bahamas","englishName":"Bahamas","countryId":199,"countryName":"Bahamas"},
  173: {"leagueId":173,"leagueName":"Ruanda","englishName":"Rwanda","countryId":200,"countryName":"Rwanda"},
  174: {"leagueId":174,"leagueName":"Saint Kitts e Nevis","englishName":"Saint Kitts and Nevis","countryId":202,"countryName":"Saint Kitts and Nevis"},
  175: {"leagueId":175,"leagueName":"Guinea Equatoriale","englishName":"Guinea Ecuatorial","countryId":201,"countryName":"Guinea Ecuatorial"},
  176: {"leagueId":176,"leagueName":"Gibilterra","englishName":"Gibraltar","countryId":203,"countryName":"Gibraltar"},
  177: {"leagueId":177,"leagueName":"Bhutan","englishName":"Bhutan","countryId":204,"countryName":"Bhutan"},
  // Hattrick International is omitted by the supplied worldDetails response,
  // but is a known countryless parent league used by the application.
  1000: { leagueId: 1000, leagueName: 'Hattrick International', englishName: 'Hattrick International', countryId: null, countryName: null },
  1001: {"leagueId":1001,"leagueName":"Campionato Apache (Edizione limitata)","englishName":"Apache League","countryId":null,"countryName":null},
  1002: {"leagueId":1002,"leagueName":"Hattrick Anniversary League","englishName":"Hattrick Anniversary League","countryId":null,"countryName":null},
  1003: {"leagueId":1003,"leagueName":"Homegrown League","englishName":"Homegrown League","countryId":null,"countryName":null},
  3000: {"leagueId":3000,"leagueName":"Hattrick Femme International","englishName":"Hattrick Femme International","countryId":null,"countryName":null},
};

export const COUNTRY_ID_TO_WORLD_LEAGUE = Object.fromEntries(
  Object.values(HATTRICK_WORLD_DETAILS)
    .filter((entry) => entry.countryId !== null)
    .map((entry) => [entry.countryId, entry]),
) as Record<number, HattrickWorldLeague>;

export function getCountryWorldDetails(countryId?: number | null): HattrickWorldLeague | null {
  return countryId == null ? null : COUNTRY_ID_TO_WORLD_LEAGUE[countryId] ?? null;
}

export function getLeagueWorldDetails(leagueId?: number | null): HattrickWorldLeague | null {
  return leagueId == null ? null : HATTRICK_WORLD_DETAILS[leagueId] ?? null;
}
