// Generated from src/utils/worlddetails.xml (CHPP worldDetails v1.2).
// leagueName is the short English display name; fullName is the full English name.
// countryName preserves Hattrick's local/original country name.
// LeagueID and CountryID are separate namespaces; special leagues have no country.
export interface HattrickWorldLeague {
  leagueId: number;
  /** Short display name used throughout the UI. */
  leagueName: string;
  /** Full English name for tooltips and explanatory copy. */
  fullName: string;
  countryId: number | null;
  countryName: string | null;
  countryNameEn: string | null;
  isoCode: string | null;
  emoji: string;
  suffix?: string;
}

export const HATTRICK_WORLD_DETAILS: Record<number, HattrickWorldLeague> = {
  1: {
    leagueId: 1,
    leagueName: 'Sweden',
    fullName: 'Sweden',
    countryId: 1,
    countryName: 'Sverige',
    countryNameEn: 'Sweden',
    isoCode: 'SE',
    emoji: '🇸🇪',
  },
  2: {
    leagueId: 2,
    leagueName: 'England',
    fullName: 'England',
    countryId: 2,
    countryName: 'England',
    countryNameEn: 'England',
    isoCode: 'GB-ENG',
    emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  },
  3: {
    leagueId: 3,
    leagueName: 'Germany',
    fullName: 'Germany',
    countryId: 3,
    countryName: 'Deutschland',
    countryNameEn: 'Germany',
    isoCode: 'DE',
    emoji: '🇩🇪',
  },
  4: {
    leagueId: 4,
    leagueName: 'Italy',
    fullName: 'Italy',
    countryId: 4,
    countryName: 'Italia',
    countryNameEn: 'Italy',
    isoCode: 'IT',
    emoji: '🇮🇹',
  },
  5: {
    leagueId: 5,
    leagueName: 'France',
    fullName: 'France',
    countryId: 5,
    countryName: 'France',
    countryNameEn: 'France',
    isoCode: 'FR',
    emoji: '🇫🇷',
  },
  6: {
    leagueId: 6,
    leagueName: 'Mexico',
    fullName: 'Mexico',
    countryId: 6,
    countryName: 'México',
    countryNameEn: 'Mexico',
    isoCode: 'MX',
    emoji: '🇲🇽',
  },
  7: {
    leagueId: 7,
    leagueName: 'Argentina',
    fullName: 'Argentina',
    countryId: 7,
    countryName: 'Argentina',
    countryNameEn: 'Argentina',
    isoCode: 'AR',
    emoji: '🇦🇷',
  },
  8: {
    leagueId: 8,
    leagueName: 'USA',
    fullName: 'United States of America',
    countryId: 8,
    countryName: 'USA',
    countryNameEn: null,
    isoCode: 'US',
    emoji: '🇺🇸',
  },
  9: {
    leagueId: 9,
    leagueName: 'Norway',
    fullName: 'Norway',
    countryId: 9,
    countryName: 'Norge',
    countryNameEn: 'Norway',
    isoCode: 'NO',
    emoji: '🇳🇴',
  },
  11: {
    leagueId: 11,
    leagueName: 'Denmark',
    fullName: 'Denmark',
    countryId: 10,
    countryName: 'Danmark',
    countryNameEn: 'Denmark',
    isoCode: 'DK',
    emoji: '🇩🇰',
  },
  12: {
    leagueId: 12,
    leagueName: 'Finland',
    fullName: 'Finland',
    countryId: 11,
    countryName: 'Suomi',
    countryNameEn: 'Finland',
    isoCode: 'FI',
    emoji: '🇫🇮',
  },
  14: {
    leagueId: 14,
    leagueName: 'Netherlands',
    fullName: 'Netherlands',
    countryId: 12,
    countryName: 'Nederland',
    countryNameEn: 'Netherlands',
    isoCode: 'NL',
    emoji: '🇳🇱',
  },
  15: {
    leagueId: 15,
    leagueName: 'Oceania',
    fullName: 'Oceania',
    countryId: 13,
    countryName: 'Oceania',
    countryNameEn: 'Oceania',
    isoCode: null,
    emoji: '🌏',
  },
  16: {
    leagueId: 16,
    leagueName: 'Brazil',
    fullName: 'Brazil',
    countryId: 22,
    countryName: 'Brasil',
    countryNameEn: 'Brazil',
    isoCode: 'BR',
    emoji: '🇧🇷',
  },
  17: {
    leagueId: 17,
    leagueName: 'Canada',
    fullName: 'Canada',
    countryId: 14,
    countryName: 'Canada',
    countryNameEn: 'Canada',
    isoCode: 'CA',
    emoji: '🇨🇦',
  },
  18: {
    leagueId: 18,
    leagueName: 'Chile',
    fullName: 'Chile',
    countryId: 17,
    countryName: 'Chile',
    countryNameEn: 'Chile',
    isoCode: 'CL',
    emoji: '🇨🇱',
  },
  19: {
    leagueId: 19,
    leagueName: 'Colombia',
    fullName: 'Colombia',
    countryId: 18,
    countryName: 'Colombia',
    countryNameEn: 'Colombia',
    isoCode: 'CO',
    emoji: '🇨🇴',
  },
  20: {
    leagueId: 20,
    leagueName: 'India',
    fullName: 'India',
    countryId: 27,
    countryName: 'India',
    countryNameEn: 'India',
    isoCode: 'IN',
    emoji: '🇮🇳',
  },
  21: {
    leagueId: 21,
    leagueName: 'Ireland',
    fullName: 'Ireland',
    countryId: 16,
    countryName: 'Ireland',
    countryNameEn: 'Ireland',
    isoCode: 'IE',
    emoji: '🇮🇪',
  },
  22: {
    leagueId: 22,
    leagueName: 'Japan',
    fullName: 'Japan',
    countryId: 25,
    countryName: 'Nippon',
    countryNameEn: 'Japan',
    isoCode: 'JP',
    emoji: '🇯🇵',
  },
  23: {
    leagueId: 23,
    leagueName: 'Peru',
    fullName: 'Peru',
    countryId: 21,
    countryName: 'Perú',
    countryNameEn: 'Peru',
    isoCode: 'PE',
    emoji: '🇵🇪',
  },
  24: {
    leagueId: 24,
    leagueName: 'Poland',
    fullName: 'Poland',
    countryId: 26,
    countryName: 'Polska',
    countryNameEn: 'Poland',
    isoCode: 'PL',
    emoji: '🇵🇱',
  },
  25: {
    leagueId: 25,
    leagueName: 'Portugal',
    fullName: 'Portugal',
    countryId: 23,
    countryName: 'Portugal',
    countryNameEn: 'Portugal',
    isoCode: 'PT',
    emoji: '🇵🇹',
  },
  26: {
    leagueId: 26,
    leagueName: 'Scotland',
    fullName: 'Scotland',
    countryId: 15,
    countryName: 'Scotland',
    countryNameEn: 'Scotland',
    isoCode: 'GB-SCT',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  },
  27: {
    leagueId: 27,
    leagueName: 'South Africa',
    fullName: 'South Africa',
    countryId: 24,
    countryName: 'South Africa',
    countryNameEn: 'South Africa',
    isoCode: 'ZA',
    emoji: '🇿🇦',
  },
  28: {
    leagueId: 28,
    leagueName: 'Uruguay',
    fullName: 'Uruguay',
    countryId: 19,
    countryName: 'Uruguay',
    countryNameEn: 'Uruguay',
    isoCode: 'UY',
    emoji: '🇺🇾',
  },
  29: {
    leagueId: 29,
    leagueName: 'Venezuela',
    fullName: 'Venezuela',
    countryId: 20,
    countryName: 'Venezuela',
    countryNameEn: 'Venezuela',
    isoCode: 'VE',
    emoji: '🇻🇪',
  },
  30: {
    leagueId: 30,
    leagueName: 'South Korea',
    fullName: 'South Korea',
    countryId: 29,
    countryName: 'Hanguk',
    countryNameEn: 'South Korea',
    isoCode: 'KR',
    emoji: '🇰🇷',
  },
  31: {
    leagueId: 31,
    leagueName: 'Thailand',
    fullName: 'Thailand',
    countryId: 30,
    countryName: 'Prathet Thai',
    countryNameEn: 'Thailand',
    isoCode: 'TH',
    emoji: '🇹🇭',
  },
  32: {
    leagueId: 32,
    leagueName: 'Turkey',
    fullName: 'Turkey',
    countryId: 31,
    countryName: 'Türkiye',
    countryNameEn: 'Turkey',
    isoCode: 'TR',
    emoji: '🇹🇷',
  },
  33: {
    leagueId: 33,
    leagueName: 'Egypt',
    fullName: 'Egypt',
    countryId: 32,
    countryName: 'Misr',
    countryNameEn: 'Egypt',
    isoCode: 'EG',
    emoji: '🇪🇬',
  },
  34: {
    leagueId: 34,
    leagueName: 'China',
    fullName: "People's Republic of China",
    countryId: 28,
    countryName: 'China',
    countryNameEn: 'China',
    isoCode: 'CN',
    emoji: '🇨🇳',
  },
  35: {
    leagueId: 35,
    leagueName: 'Russia',
    fullName: 'Russia',
    countryId: 34,
    countryName: 'Rossiya',
    countryNameEn: 'Russia',
    isoCode: 'RU',
    emoji: '🇷🇺',
  },
  36: {
    leagueId: 36,
    leagueName: 'Spain',
    fullName: 'Spain',
    countryId: 35,
    countryName: 'España',
    countryNameEn: 'Spain',
    isoCode: 'ES',
    emoji: '🇪🇸',
  },
  37: {
    leagueId: 37,
    leagueName: 'Romania',
    fullName: 'Romania',
    countryId: 36,
    countryName: 'România',
    countryNameEn: 'Romania',
    isoCode: 'RO',
    emoji: '🇷🇴',
  },
  38: {
    leagueId: 38,
    leagueName: 'Iceland',
    fullName: 'Iceland',
    countryId: 37,
    countryName: 'Ísland',
    countryNameEn: 'Iceland',
    isoCode: 'IS',
    emoji: '🇮🇸',
  },
  39: {
    leagueId: 39,
    leagueName: 'Austria',
    fullName: 'Austria',
    countryId: 33,
    countryName: 'Österreich',
    countryNameEn: 'Austria',
    isoCode: 'AT',
    emoji: '🇦🇹',
  },
  44: {
    leagueId: 44,
    leagueName: 'Belgium',
    fullName: 'Belgium',
    countryId: 38,
    countryName: 'Belgium',
    countryNameEn: 'Belgium',
    isoCode: 'BE',
    emoji: '🇧🇪',
  },
  45: {
    leagueId: 45,
    leagueName: 'Malaysia',
    fullName: 'Malaysia',
    countryId: 39,
    countryName: 'Malaysia',
    countryNameEn: 'Malaysia',
    isoCode: 'MY',
    emoji: '🇲🇾',
  },
  46: {
    leagueId: 46,
    leagueName: 'Switzerland',
    fullName: 'Switzerland',
    countryId: 40,
    countryName: 'Schweiz',
    countryNameEn: 'Switzerland',
    isoCode: 'CH',
    emoji: '🇨🇭',
  },
  47: {
    leagueId: 47,
    leagueName: 'Singapore',
    fullName: 'Singapore',
    countryId: 41,
    countryName: 'Singapore',
    countryNameEn: 'Singapore',
    isoCode: 'SG',
    emoji: '🇸🇬',
  },
  50: {
    leagueId: 50,
    leagueName: 'Greece',
    fullName: 'Greece',
    countryId: 45,
    countryName: 'Hellas',
    countryNameEn: 'Greece',
    isoCode: 'GR',
    emoji: '🇬🇷',
  },
  51: {
    leagueId: 51,
    leagueName: 'Hungary',
    fullName: 'Hungary',
    countryId: 44,
    countryName: 'Magyarország',
    countryNameEn: 'Hungary',
    isoCode: 'HU',
    emoji: '🇭🇺',
  },
  52: {
    leagueId: 52,
    leagueName: 'Czechia',
    fullName: 'Czechia',
    countryId: 46,
    countryName: 'Česko',
    countryNameEn: 'Czechia',
    isoCode: 'CZ',
    emoji: '🇨🇿',
  },
  53: {
    leagueId: 53,
    leagueName: 'Latvia',
    fullName: 'Latvia',
    countryId: 48,
    countryName: 'Latvija',
    countryNameEn: 'Latvia',
    isoCode: 'LV',
    emoji: '🇱🇻',
  },
  54: {
    leagueId: 54,
    leagueName: 'Indonesia',
    fullName: 'Indonesia',
    countryId: 49,
    countryName: 'Indonesia',
    countryNameEn: 'Indonesia',
    isoCode: 'ID',
    emoji: '🇮🇩',
  },
  55: {
    leagueId: 55,
    leagueName: 'Philippines',
    fullName: 'Philippines',
    countryId: 50,
    countryName: 'Pilipinas',
    countryNameEn: 'Philippines',
    isoCode: 'PH',
    emoji: '🇵🇭',
  },
  56: {
    leagueId: 56,
    leagueName: 'Estonia',
    fullName: 'Estonia',
    countryId: 47,
    countryName: 'Eesti',
    countryNameEn: 'Estonia',
    isoCode: 'EE',
    emoji: '🇪🇪',
  },
  57: {
    leagueId: 57,
    leagueName: 'Serbia',
    fullName: 'Serbia',
    countryId: 43,
    countryName: 'Srbija',
    countryNameEn: 'Serbia',
    isoCode: 'RS',
    emoji: '🇷🇸',
  },
  58: {
    leagueId: 58,
    leagueName: 'Croatia',
    fullName: 'Croatia',
    countryId: 42,
    countryName: 'Hrvatska',
    countryNameEn: 'Croatia',
    isoCode: 'HR',
    emoji: '🇭🇷',
  },
  59: {
    leagueId: 59,
    leagueName: 'Hong Kong',
    fullName: 'Hong Kong',
    countryId: 53,
    countryName: 'Hong Kong, China',
    countryNameEn: 'Hong Kong',
    isoCode: 'HK',
    emoji: '🇭🇰',
  },
  60: {
    leagueId: 60,
    leagueName: 'Chinese Taipei',
    fullName: 'Chinese Taipei',
    countryId: 52,
    countryName: 'Chinese Taipei',
    countryNameEn: 'Chinese Taipei',
    isoCode: 'TW',
    emoji: '🇹🇼',
  },
  61: {
    leagueId: 61,
    leagueName: 'Wales',
    fullName: 'Wales',
    countryId: 56,
    countryName: 'Cymru',
    countryNameEn: 'Wales',
    isoCode: 'GB-WLS',
    emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  },
  62: {
    leagueId: 62,
    leagueName: 'Bulgaria',
    fullName: 'Bulgaria',
    countryId: 55,
    countryName: 'Bulgaria',
    countryNameEn: 'Bulgaria',
    isoCode: 'BG',
    emoji: '🇧🇬',
  },
  63: {
    leagueId: 63,
    leagueName: 'Israel',
    fullName: 'Israel',
    countryId: 51,
    countryName: 'Israel',
    countryNameEn: 'Israel',
    isoCode: 'IL',
    emoji: '🇮🇱',
  },
  64: {
    leagueId: 64,
    leagueName: 'Slovenia',
    fullName: 'Slovenia',
    countryId: 57,
    countryName: 'Slovenija',
    countryNameEn: 'Slovenia',
    isoCode: 'SI',
    emoji: '🇸🇮',
  },
  66: {
    leagueId: 66,
    leagueName: 'Lithuania',
    fullName: 'Lithuania',
    countryId: 61,
    countryName: 'Lietuva',
    countryNameEn: 'Lithuania',
    isoCode: 'LT',
    emoji: '🇱🇹',
  },
  67: {
    leagueId: 67,
    leagueName: 'Slovakia',
    fullName: 'Slovakia',
    countryId: 66,
    countryName: 'Slovensko',
    countryNameEn: 'Slovakia',
    isoCode: 'SK',
    emoji: '🇸🇰',
  },
  68: {
    leagueId: 68,
    leagueName: 'Ukraine',
    fullName: 'Ukraine',
    countryId: 62,
    countryName: 'Ukraina',
    countryNameEn: 'Ukraine',
    isoCode: 'UA',
    emoji: '🇺🇦',
  },
  69: {
    leagueId: 69,
    leagueName: 'Bosnia and Herzegovina',
    fullName: 'Bosnia and Herzegovina',
    countryId: 63,
    countryName: 'Bosna i Hercegovina',
    countryNameEn: 'Bosnia and Herzegovina',
    isoCode: 'BA',
    emoji: '🇧🇦',
  },
  70: {
    leagueId: 70,
    leagueName: 'Vietnam',
    fullName: 'Vietnam',
    countryId: 65,
    countryName: 'Việt Nam',
    countryNameEn: 'Vietnam',
    isoCode: 'VN',
    emoji: '🇻🇳',
  },
  71: {
    leagueId: 71,
    leagueName: 'Pakistan',
    fullName: 'Pakistan',
    countryId: 64,
    countryName: 'Pakistan',
    countryNameEn: 'Pakistan',
    isoCode: 'PK',
    emoji: '🇵🇰',
  },
  72: {
    leagueId: 72,
    leagueName: 'Paraguay',
    fullName: 'Paraguay',
    countryId: 67,
    countryName: 'Paraguay',
    countryNameEn: 'Paraguay',
    isoCode: 'PY',
    emoji: '🇵🇾',
  },
  73: {
    leagueId: 73,
    leagueName: 'Ecuador',
    fullName: 'Ecuador',
    countryId: 68,
    countryName: 'Ecuador',
    countryNameEn: 'Ecuador',
    isoCode: 'EC',
    emoji: '🇪🇨',
  },
  74: {
    leagueId: 74,
    leagueName: 'Bolivia',
    fullName: 'Bolivia',
    countryId: 69,
    countryName: 'Bolivia',
    countryNameEn: 'Bolivia',
    isoCode: 'BO',
    emoji: '🇧🇴',
  },
  75: {
    leagueId: 75,
    leagueName: 'Nigeria',
    fullName: 'Nigeria',
    countryId: 70,
    countryName: 'Nigeria',
    countryNameEn: 'Nigeria',
    isoCode: 'NG',
    emoji: '🇳🇬',
  },
  76: {
    leagueId: 76,
    leagueName: 'Faroe Islands',
    fullName: 'Faroe Islands',
    countryId: 71,
    countryName: 'Føroyar',
    countryNameEn: 'Faroe Islands',
    isoCode: 'FO',
    emoji: '🇫🇴',
  },
  77: {
    leagueId: 77,
    leagueName: 'Morocco',
    fullName: 'Morocco',
    countryId: 72,
    countryName: 'Al Maghrib',
    countryNameEn: 'Morocco',
    isoCode: 'MA',
    emoji: '🇲🇦',
  },
  79: {
    leagueId: 79,
    leagueName: 'Saudi Arabia',
    fullName: 'Saudi Arabia',
    countryId: 75,
    countryName: 'Saudi Arabia',
    countryNameEn: 'Saudi Arabia',
    isoCode: 'SA',
    emoji: '🇸🇦',
  },
  80: {
    leagueId: 80,
    leagueName: 'Tunisia',
    fullName: 'Tunisia',
    countryId: 76,
    countryName: 'Tounes',
    countryNameEn: 'Tunisia',
    isoCode: 'TN',
    emoji: '🇹🇳',
  },
  81: {
    leagueId: 81,
    leagueName: 'Costa Rica',
    fullName: 'Costa Rica',
    countryId: 77,
    countryName: 'Costa Rica',
    countryNameEn: 'Costa Rica',
    isoCode: 'CR',
    emoji: '🇨🇷',
  },
  83: {
    leagueId: 83,
    leagueName: 'United Arab Emirates',
    fullName: 'United Arab Emirates',
    countryId: 78,
    countryName: 'United Arab Emirates',
    countryNameEn: 'United Arab Emirates',
    isoCode: 'AE',
    emoji: '🇦🇪',
  },
  84: {
    leagueId: 84,
    leagueName: 'Luxembourg',
    fullName: 'Luxembourg',
    countryId: 79,
    countryName: 'Lëtzebuerg',
    countryNameEn: 'Luxembourg',
    isoCode: 'LU',
    emoji: '🇱🇺',
  },
  85: {
    leagueId: 85,
    leagueName: 'Iran',
    fullName: 'Iran',
    countryId: 80,
    countryName: 'Iran',
    countryNameEn: 'Iran',
    isoCode: 'IR',
    emoji: '🇮🇷',
  },
  88: {
    leagueId: 88,
    leagueName: 'Dominican Republic',
    fullName: 'Dominican Republic',
    countryId: 83,
    countryName: 'República Dominicana',
    countryNameEn: 'Dominican Republic',
    isoCode: 'DO',
    emoji: '🇩🇴',
  },
  89: {
    leagueId: 89,
    leagueName: 'Cyprus',
    fullName: 'Cyprus',
    countryId: 82,
    countryName: 'Cyprus',
    countryNameEn: 'Cyprus',
    isoCode: 'CY',
    emoji: '🇨🇾',
  },
  91: {
    leagueId: 91,
    leagueName: 'Belarus',
    fullName: 'Belarus',
    countryId: 87,
    countryName: 'Belarus',
    countryNameEn: 'Belarus',
    isoCode: 'BY',
    emoji: '🇧🇾',
  },
  93: {
    leagueId: 93,
    leagueName: 'Northern Ireland',
    fullName: 'Northern Ireland',
    countryId: 88,
    countryName: 'Northern Ireland',
    countryNameEn: 'Northern Ireland',
    isoCode: 'GB-NIR',
    emoji: '🇬🇧',
  },
  94: {
    leagueId: 94,
    leagueName: 'Jamaica',
    fullName: 'Jamaica',
    countryId: 89,
    countryName: 'Jamaica',
    countryNameEn: 'Jamaica',
    isoCode: 'JM',
    emoji: '🇯🇲',
  },
  95: {
    leagueId: 95,
    leagueName: 'Kenya',
    fullName: 'Kenya',
    countryId: 90,
    countryName: 'Kenya',
    countryNameEn: 'Kenya',
    isoCode: 'KE',
    emoji: '🇰🇪',
  },
  96: {
    leagueId: 96,
    leagueName: 'Panama',
    fullName: 'Panama',
    countryId: 91,
    countryName: 'Panamá',
    countryNameEn: 'Panama',
    isoCode: 'PA',
    emoji: '🇵🇦',
  },
  97: {
    leagueId: 97,
    leagueName: 'North Macedonia',
    fullName: 'North Macedonia',
    countryId: 92,
    countryName: 'Severna Makedonija',
    countryNameEn: 'North Macedonia',
    isoCode: 'MK',
    emoji: '🇲🇰',
  },
  98: {
    leagueId: 98,
    leagueName: 'Albania',
    fullName: 'Albania',
    countryId: 94,
    countryName: 'Shqipëria',
    countryNameEn: 'Albania',
    isoCode: 'AL',
    emoji: '🇦🇱',
  },
  99: {
    leagueId: 99,
    leagueName: 'Honduras',
    fullName: 'Honduras',
    countryId: 95,
    countryName: 'Honduras',
    countryNameEn: 'Honduras',
    isoCode: 'HN',
    emoji: '🇭🇳',
  },
  100: {
    leagueId: 100,
    leagueName: 'El Salvador',
    fullName: 'El Salvador',
    countryId: 96,
    countryName: 'El Salvador',
    countryNameEn: 'El Salvador',
    isoCode: 'SV',
    emoji: '🇸🇻',
  },
  101: {
    leagueId: 101,
    leagueName: 'Malta',
    fullName: 'Malta',
    countryId: 97,
    countryName: 'Malta',
    countryNameEn: 'Malta',
    isoCode: 'MT',
    emoji: '🇲🇹',
  },
  102: {
    leagueId: 102,
    leagueName: 'Kyrgyzstan',
    fullName: 'Kyrgyz Republic',
    countryId: 98,
    countryName: 'Kyrgyz Republic',
    countryNameEn: 'Kyrgyzstan',
    isoCode: 'KG',
    emoji: '🇰🇬',
  },
  103: {
    leagueId: 103,
    leagueName: 'Moldova',
    fullName: 'Moldova',
    countryId: 99,
    countryName: 'Moldova',
    countryNameEn: 'Moldova',
    isoCode: 'MD',
    emoji: '🇲🇩',
  },
  104: {
    leagueId: 104,
    leagueName: 'Georgia',
    fullName: 'Georgia',
    countryId: 100,
    countryName: 'Sakartvelo',
    countryNameEn: 'Georgia',
    isoCode: 'GE',
    emoji: '🇬🇪',
  },
  105: {
    leagueId: 105,
    leagueName: 'Andorra',
    fullName: 'Andorra',
    countryId: 101,
    countryName: 'Andorra',
    countryNameEn: 'Andorra',
    isoCode: 'AD',
    emoji: '🇦🇩',
  },
  106: {
    leagueId: 106,
    leagueName: 'Jordan',
    fullName: 'Jordan',
    countryId: 103,
    countryName: 'Al Urdun',
    countryNameEn: 'Jordan',
    isoCode: 'JO',
    emoji: '🇯🇴',
  },
  107: {
    leagueId: 107,
    leagueName: 'Guatemala',
    fullName: 'Guatemala',
    countryId: 102,
    countryName: 'Guatemala',
    countryNameEn: 'Guatemala',
    isoCode: 'GT',
    emoji: '🇬🇹',
  },
  110: {
    leagueId: 110,
    leagueName: 'Trinidad & Tobago',
    fullName: 'Trinidad & Tobago',
    countryId: 105,
    countryName: 'Trinidad & Tobago',
    countryNameEn: 'Trinidad & Tobago',
    isoCode: 'TT',
    emoji: '🇹🇹',
  },
  111: {
    leagueId: 111,
    leagueName: 'Nicaragua',
    fullName: 'Nicaragua',
    countryId: 121,
    countryName: 'Nicaragua',
    countryNameEn: 'Nicaragua',
    isoCode: 'NI',
    emoji: '🇳🇮',
  },
  112: {
    leagueId: 112,
    leagueName: 'Kazakhstan',
    fullName: 'Kazakhstan',
    countryId: 122,
    countryName: 'Kazakhstan',
    countryNameEn: 'Kazakhstan',
    isoCode: 'KZ',
    emoji: '🇰🇿',
  },
  113: {
    leagueId: 113,
    leagueName: 'Suriname',
    fullName: 'Suriname',
    countryId: 123,
    countryName: 'Suriname',
    countryNameEn: 'Suriname',
    isoCode: 'SR',
    emoji: '🇸🇷',
  },
  117: {
    leagueId: 117,
    leagueName: 'Liechtenstein',
    fullName: 'Liechtenstein',
    countryId: 125,
    countryName: 'Liechtenstein',
    countryNameEn: 'Liechtenstein',
    isoCode: 'LI',
    emoji: '🇱🇮',
  },
  118: {
    leagueId: 118,
    leagueName: 'Algeria',
    fullName: 'Algeria',
    countryId: 126,
    countryName: 'Algérie',
    countryNameEn: 'Algeria',
    isoCode: 'DZ',
    emoji: '🇩🇿',
  },
  119: {
    leagueId: 119,
    leagueName: 'Mongolia',
    fullName: 'Mongolia',
    countryId: 127,
    countryName: 'Mongol Uls',
    countryNameEn: 'Mongolia',
    isoCode: 'MN',
    emoji: '🇲🇳',
  },
  120: {
    leagueId: 120,
    leagueName: 'Lebanon',
    fullName: 'Lebanon',
    countryId: 128,
    countryName: 'Lebanon',
    countryNameEn: 'Lebanon',
    isoCode: 'LB',
    emoji: '🇱🇧',
  },
  121: {
    leagueId: 121,
    leagueName: 'Senegal',
    fullName: 'Senegal',
    countryId: 86,
    countryName: 'Sénégal',
    countryNameEn: 'Senegal',
    isoCode: 'SN',
    emoji: '🇸🇳',
  },
  122: {
    leagueId: 122,
    leagueName: 'Armenia',
    fullName: 'Armenia',
    countryId: 104,
    countryName: 'Armenia',
    countryNameEn: 'Armenia',
    isoCode: 'AM',
    emoji: '🇦🇲',
  },
  123: {
    leagueId: 123,
    leagueName: 'Bahrain',
    fullName: 'Bahrain',
    countryId: 129,
    countryName: 'Bahrain',
    countryNameEn: 'Bahrain',
    isoCode: 'BH',
    emoji: '🇧🇭',
  },
  124: {
    leagueId: 124,
    leagueName: 'Barbados',
    fullName: 'Barbados',
    countryId: 130,
    countryName: 'Barbados',
    countryNameEn: 'Barbados',
    isoCode: 'BB',
    emoji: '🇧🇧',
  },
  125: {
    leagueId: 125,
    leagueName: 'Cape Verde',
    fullName: 'Cape Verde',
    countryId: 131,
    countryName: 'Cabo Verde',
    countryNameEn: 'Cape Verde',
    isoCode: 'CV',
    emoji: '🇨🇻',
  },
  126: {
    leagueId: 126,
    leagueName: 'Ivory Coast',
    fullName: 'Côte d’Ivoire',
    countryId: 132,
    countryName: 'Côte d’Ivoire',
    countryNameEn: 'Ivory Coast',
    isoCode: 'CI',
    emoji: '🇨🇮',
  },
  127: {
    leagueId: 127,
    leagueName: 'Kuwait',
    fullName: 'Kuwait',
    countryId: 134,
    countryName: 'Al Kuwayt',
    countryNameEn: 'Kuwait',
    isoCode: 'KW',
    emoji: '🇰🇼',
  },
  128: {
    leagueId: 128,
    leagueName: 'Iraq',
    fullName: 'Iraq',
    countryId: 135,
    countryName: 'Al Iraq',
    countryNameEn: 'Iraq',
    isoCode: 'IQ',
    emoji: '🇮🇶',
  },
  129: {
    leagueId: 129,
    leagueName: 'Azerbaijan',
    fullName: 'Azerbaijan',
    countryId: 133,
    countryName: 'Azərbaycan',
    countryNameEn: 'Azerbaijan',
    isoCode: 'AZ',
    emoji: '🇦🇿',
  },
  130: {
    leagueId: 130,
    leagueName: 'Angola',
    fullName: 'Angola',
    countryId: 137,
    countryName: 'Angola',
    countryNameEn: 'Angola',
    isoCode: 'AO',
    emoji: '🇦🇴',
  },
  131: {
    leagueId: 131,
    leagueName: 'Montenegro',
    fullName: 'Montenegro',
    countryId: 136,
    countryName: 'Crna Gora',
    countryNameEn: 'Montenegro',
    isoCode: 'ME',
    emoji: '🇲🇪',
  },
  132: {
    leagueId: 132,
    leagueName: 'Bangladesh',
    fullName: 'Bangladesh',
    countryId: 138,
    countryName: 'Bangladesh',
    countryNameEn: 'Bangladesh',
    isoCode: 'BD',
    emoji: '🇧🇩',
  },
  133: {
    leagueId: 133,
    leagueName: 'Yemen',
    fullName: 'Yemen',
    countryId: 139,
    countryName: 'Al Yaman',
    countryNameEn: 'Yemen',
    isoCode: 'YE',
    emoji: '🇾🇪',
  },
  134: {
    leagueId: 134,
    leagueName: 'Oman',
    fullName: 'Oman',
    countryId: 140,
    countryName: 'Oman',
    countryNameEn: 'Oman',
    isoCode: 'OM',
    emoji: '🇴🇲',
  },
  135: {
    leagueId: 135,
    leagueName: 'Mozambique',
    fullName: 'Mozambique',
    countryId: 142,
    countryName: 'Moçambique',
    countryNameEn: 'Mozambique',
    isoCode: 'MZ',
    emoji: '🇲🇿',
  },
  136: {
    leagueId: 136,
    leagueName: 'Brunei',
    fullName: 'Brunei',
    countryId: 143,
    countryName: 'Brunei',
    countryNameEn: 'Brunei',
    isoCode: 'BN',
    emoji: '🇧🇳',
  },
  137: {
    leagueId: 137,
    leagueName: 'Ghana',
    fullName: 'Ghana',
    countryId: 144,
    countryName: 'Ghana',
    countryNameEn: 'Ghana',
    isoCode: 'GH',
    emoji: '🇬🇭',
  },
  138: {
    leagueId: 138,
    leagueName: 'Cambodia',
    fullName: 'Cambodia',
    countryId: 145,
    countryName: 'Kampuchea',
    countryNameEn: 'Cambodia',
    isoCode: 'KH',
    emoji: '🇰🇭',
  },
  139: {
    leagueId: 139,
    leagueName: 'Benin',
    fullName: 'Benin',
    countryId: 147,
    countryName: 'Benin',
    countryNameEn: 'Benin',
    isoCode: 'BJ',
    emoji: '🇧🇯',
  },
  140: {
    leagueId: 140,
    leagueName: 'Syria',
    fullName: 'Syria',
    countryId: 148,
    countryName: 'Suriyah',
    countryNameEn: 'Syria',
    isoCode: 'SY',
    emoji: '🇸🇾',
  },
  141: {
    leagueId: 141,
    leagueName: 'Qatar',
    fullName: 'Qatar',
    countryId: 149,
    countryName: 'Qatar',
    countryNameEn: 'Qatar',
    isoCode: 'QA',
    emoji: '🇶🇦',
  },
  142: {
    leagueId: 142,
    leagueName: 'Tanzania',
    fullName: 'Tanzania',
    countryId: 150,
    countryName: 'Tanzania',
    countryNameEn: 'Tanzania',
    isoCode: 'TZ',
    emoji: '🇹🇿',
  },
  143: {
    leagueId: 143,
    leagueName: 'Uganda',
    fullName: 'Uganda',
    countryId: 153,
    countryName: 'Uganda',
    countryNameEn: 'Uganda',
    isoCode: 'UG',
    emoji: '🇺🇬',
  },
  144: {
    leagueId: 144,
    leagueName: 'Maldives',
    fullName: 'Maldives',
    countryId: 154,
    countryName: 'Dhivehi Raajje',
    countryNameEn: 'Maldives',
    isoCode: 'MV',
    emoji: '🇲🇻',
  },
  145: {
    leagueId: 145,
    leagueName: 'Uzbekistan',
    fullName: 'Uzbekistan',
    countryId: 163,
    countryName: 'Uzbekistan',
    countryNameEn: 'Uzbekistan',
    isoCode: 'UZ',
    emoji: '🇺🇿',
  },
  146: {
    leagueId: 146,
    leagueName: 'Cameroon',
    fullName: 'Cameroon',
    countryId: 165,
    countryName: 'Cameroon',
    countryNameEn: 'Cameroon',
    isoCode: 'CM',
    emoji: '🇨🇲',
  },
  147: {
    leagueId: 147,
    leagueName: 'Cuba',
    fullName: 'Cuba',
    countryId: 93,
    countryName: 'Cuba',
    countryNameEn: 'Cuba',
    isoCode: 'CU',
    emoji: '🇨🇺',
  },
  148: {
    leagueId: 148,
    leagueName: 'Palestine',
    fullName: 'Palestine',
    countryId: 166,
    countryName: 'Palestine',
    countryNameEn: 'Palestine',
    isoCode: 'PS',
    emoji: '🇵🇸',
  },
  149: {
    leagueId: 149,
    leagueName: 'São Tomé e Príncipe',
    fullName: 'São Tomé e Príncipe',
    countryId: 177,
    countryName: 'São Tomé e Príncipe',
    countryNameEn: 'São Tomé e Príncipe',
    isoCode: 'ST',
    emoji: '🇸🇹',
  },
  151: {
    leagueId: 151,
    leagueName: 'Comoros',
    fullName: 'Comoros',
    countryId: 180,
    countryName: 'Comoros',
    countryNameEn: 'Comoros',
    isoCode: 'KM',
    emoji: '🇰🇲',
  },
  152: {
    leagueId: 152,
    leagueName: 'Sri Lanka',
    fullName: 'Sri Lanka',
    countryId: 175,
    countryName: 'Sri Lanka',
    countryNameEn: 'Sri Lanka',
    isoCode: 'LK',
    emoji: '🇱🇰',
  },
  153: {
    leagueId: 153,
    leagueName: 'Curaçao',
    fullName: 'Curaçao',
    countryId: 178,
    countryName: 'Curaçao',
    countryNameEn: 'Curaçao',
    isoCode: 'CW',
    emoji: '🇨🇼',
  },
  154: {
    leagueId: 154,
    leagueName: 'Guam',
    fullName: 'Guam',
    countryId: 179,
    countryName: 'Guam',
    countryNameEn: 'Guam',
    isoCode: 'GU',
    emoji: '🇬🇺',
  },
  155: {
    leagueId: 155,
    leagueName: 'DRC',
    fullName: 'Democratic Republic of the Congo',
    countryId: 181,
    countryName: 'DR Congo',
    countryNameEn: 'DRC',
    isoCode: 'CD',
    emoji: '🇨🇩',
  },
  156: {
    leagueId: 156,
    leagueName: 'Ethiopia',
    fullName: 'Federal Democratic Republic of Ethiopia',
    countryId: 182,
    countryName: 'Ethiopia',
    countryNameEn: 'Ethiopia',
    isoCode: 'ET',
    emoji: '🇪🇹',
  },
  157: {
    leagueId: 157,
    leagueName: 'Saint Vincent and the Grenadines',
    fullName: 'Saint Vincent and the Grenadines',
    countryId: 184,
    countryName: 'Saint Vincent and the Grenadines',
    countryNameEn: 'Saint Vincent and the Grenadines',
    isoCode: 'VC',
    emoji: '🇻🇨',
  },
  158: {
    leagueId: 158,
    leagueName: 'Belize',
    fullName: 'Belize',
    countryId: 186,
    countryName: 'Belize',
    countryNameEn: 'Belize',
    isoCode: 'BZ',
    emoji: '🇧🇿',
  },
  159: {
    leagueId: 159,
    leagueName: 'Madagascar',
    fullName: 'Madagascar',
    countryId: 183,
    countryName: 'Madagascar',
    countryNameEn: 'Madagascar',
    isoCode: 'MG',
    emoji: '🇲🇬',
  },
  160: {
    leagueId: 160,
    leagueName: 'Botswana',
    fullName: 'Botswana',
    countryId: 185,
    countryName: 'Botswana',
    countryNameEn: 'Botswana',
    isoCode: 'BW',
    emoji: '🇧🇼',
  },
  161: {
    leagueId: 161,
    leagueName: 'Myanmar',
    fullName: 'Myanmar',
    countryId: 189,
    countryName: 'Myanmar',
    countryNameEn: 'Myanmar',
    isoCode: 'MM',
    emoji: '🇲🇲',
  },
  162: {
    leagueId: 162,
    leagueName: 'Zambia',
    fullName: 'Zambia',
    countryId: 187,
    countryName: 'Zambia',
    countryNameEn: 'Zambia',
    isoCode: 'ZM',
    emoji: '🇿🇲',
  },
  163: {
    leagueId: 163,
    leagueName: 'San Marino',
    fullName: 'San Marino',
    countryId: 191,
    countryName: 'San Marino',
    countryNameEn: 'San Marino',
    isoCode: 'SM',
    emoji: '🇸🇲',
  },
  164: {
    leagueId: 164,
    leagueName: 'Haiti',
    fullName: 'Haiti',
    countryId: 188,
    countryName: 'Haiti',
    countryNameEn: 'Haiti',
    isoCode: 'HT',
    emoji: '🇭🇹',
  },
  165: {
    leagueId: 165,
    leagueName: 'Puerto Rico',
    fullName: 'Puerto Rico',
    countryId: 190,
    countryName: 'Puerto Rico',
    countryNameEn: 'Puerto Rico',
    isoCode: 'PR',
    emoji: '🇵🇷',
  },
  166: {
    leagueId: 166,
    leagueName: 'Grenada',
    fullName: 'Grenada',
    countryId: 194,
    countryName: 'Grenada',
    countryNameEn: 'Grenada',
    isoCode: 'GD',
    emoji: '🇬🇩',
  },
  167: {
    leagueId: 167,
    leagueName: 'Burkina Faso',
    fullName: 'Burkina Faso',
    countryId: 193,
    countryName: 'Burkina Faso',
    countryNameEn: 'Burkina Faso',
    isoCode: 'BF',
    emoji: '🇧🇫',
  },
  168: {
    leagueId: 168,
    leagueName: 'Nepal',
    fullName: 'Nepal',
    countryId: 192,
    countryName: 'Nepal',
    countryNameEn: 'Nepal',
    isoCode: 'NP',
    emoji: '🇳🇵',
  },
  169: {
    leagueId: 169,
    leagueName: 'Guyana',
    fullName: 'Guyana',
    countryId: 197,
    countryName: 'Guyana',
    countryNameEn: 'Guyana',
    isoCode: 'GY',
    emoji: '🇬🇾',
  },
  170: {
    leagueId: 170,
    leagueName: 'Tahiti',
    fullName: 'Tahiti',
    countryId: 196,
    countryName: 'Tahiti',
    countryNameEn: 'Tahiti',
    isoCode: 'PF',
    emoji: '🇵🇫',
  },
  171: {
    leagueId: 171,
    leagueName: 'Guinea',
    fullName: 'Guinea',
    countryId: 198,
    countryName: 'Guinea',
    countryNameEn: 'Guinea',
    isoCode: 'GN',
    emoji: '🇬🇳',
  },
  172: {
    leagueId: 172,
    leagueName: 'Bahamas',
    fullName: 'Bahamas',
    countryId: 199,
    countryName: 'Bahamas',
    countryNameEn: 'Bahamas',
    isoCode: 'BS',
    emoji: '🇧🇸',
  },
  173: {
    leagueId: 173,
    leagueName: 'Rwanda',
    fullName: 'Rwanda',
    countryId: 200,
    countryName: 'Rwanda',
    countryNameEn: 'Rwanda',
    isoCode: 'RW',
    emoji: '🇷🇼',
  },
  174: {
    leagueId: 174,
    leagueName: 'Saint Kitts',
    fullName: 'Saint Kitts and Nevis',
    countryId: 202,
    countryName: 'Saint Kitts',
    countryNameEn: 'Saint Kitts',
    isoCode: 'KN',
    emoji: '🇰🇳',
  },
  175: {
    leagueId: 175,
    leagueName: 'Equatorial Guinea',
    fullName: 'Equatorial Guinea',
    countryId: 201,
    countryName: 'Guinea Ecuatorial',
    countryNameEn: 'Equatorial Guinea',
    isoCode: 'GQ',
    emoji: '🇬🇶',
  },
  176: {
    leagueId: 176,
    leagueName: 'Gibraltar',
    fullName: 'Gibraltar',
    countryId: 203,
    countryName: 'Gibraltar',
    countryNameEn: 'Gibraltar',
    isoCode: 'GI',
    emoji: '🇬🇮',
  },
  177: {
    leagueId: 177,
    leagueName: 'Bhutan',
    fullName: 'Bhutan',
    countryId: 204,
    countryName: 'Bhutan',
    countryNameEn: 'Bhutan',
    isoCode: 'BT',
    emoji: '🇧🇹',
  },
  // Hattrick International is omitted by the supplied worldDetails response,
  // but is a known countryless parent league used by the application.
  1000: {
    leagueId: 1000,
    leagueName: 'HT International',
    suffix: 'HTI',
    fullName: 'Hattrick International',
    countryId: null,
    countryName: null,
    countryNameEn: null,
    isoCode: null,
    emoji: '🇺🇳',
  },
  1001: {
    leagueId: 1001,
    leagueName: 'Apache League',
    suffix: 'AL',
    fullName: 'Apache League',
    countryId: null,
    countryName: null,
    countryNameEn: null,
    isoCode: null,
    emoji: '🇺🇳',
  },
  1002: {
    leagueId: 1002,
    leagueName: 'Anniversary',
    suffix: 'HAL',
    fullName: 'Hattrick Anniversary League',
    countryId: null,
    countryName: null,
    countryNameEn: null,
    isoCode: null,
    emoji: '🇺🇳',
  },
  1003: {
    leagueId: 1003,
    leagueName: 'Homegrown',
    suffix: 'HGL',
    fullName: 'Homegrown League',
    countryId: null,
    countryName: null,
    countryNameEn: null,
    isoCode: null,
    emoji: '❣️',
  },
  3000: {
    leagueId: 3000,
    leagueName: 'HFI',
    suffix: 'HFI',
    fullName: 'Hattrick Femme International',
    countryId: null,
    countryName: null,
    countryNameEn: null,
    isoCode: null,
    emoji: '💃🏻',
  },
};

export const COUNTRY_ID_TO_WORLD_LEAGUE = Object.fromEntries(
  Object.values(HATTRICK_WORLD_DETAILS)
    .filter((entry) => entry.countryId !== null)
    .map((entry) => [entry.countryId, entry]),
) as Record<number, HattrickWorldLeague>;

export function getCountryWorldDetails(countryId?: number | null): HattrickWorldLeague | null {
  return countryId == null ? null : (COUNTRY_ID_TO_WORLD_LEAGUE[countryId] ?? null);
}

export function getLeagueWorldDetails(leagueId?: number | null): HattrickWorldLeague | null {
  return leagueId == null ? null : (HATTRICK_WORLD_DETAILS[leagueId] ?? null);
}

export const HATTRICK_LEAGUES: Record<string, string> = Object.fromEntries(
  Object.values(HATTRICK_WORLD_DETAILS).map((league) => [String(league.leagueId), league.leagueName]),
);

export const LEAGUE_NAMES = Object.values(HATTRICK_LEAGUES);

export function getLeagueIdByName(name?: string | number | null): string | undefined {
  if (name === undefined || name === null || name === '') return undefined;
  const value = String(name).trim();
  if (value in HATTRICK_LEAGUES) return value;
  return Object.values(HATTRICK_WORLD_DETAILS)
    .find((league) => league.leagueName === value || league.fullName === value)
    ?.leagueId.toString();
}

export function getCountryIdByName(name?: string | number | null): string | undefined {
  if (name === undefined || name === null || name === '') return undefined;
  const value = String(name).trim();
  const numericId = Number(value);
  if (Number.isFinite(numericId)) {
    if (getCountryWorldDetails(numericId)) return String(numericId);
    const matchingLeague = getLeagueWorldDetails(numericId);
    return matchingLeague?.countryId == null ? undefined : String(matchingLeague.countryId);
  }

  return Object.values(HATTRICK_WORLD_DETAILS)
    .find(
      (league) =>
        league.leagueName === value ||
        league.fullName === value ||
        league.countryName === value ||
        league.countryNameEn === value,
    )
    ?.countryId?.toString();
}

export function getLeagueNameById(id?: number | string | null): string | undefined {
  if (id === undefined || id === null || id === '') return undefined;
  return HATTRICK_WORLD_DETAILS[Number(id)]?.leagueName;
}

export function getCountryNameById(id?: number | string | null): string | undefined {
  if (id === undefined || id === null || id === '') return undefined;
  return getCountryWorldDetails(Number(id))?.leagueName;
}

export function getLeagueFullNameById(id?: number | string | null): string | undefined {
  if (id === undefined || id === null || id === '') return undefined;
  return HATTRICK_WORLD_DETAILS[Number(id)]?.fullName;
}

export function normalizeLeagueLimit(value: string | number | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const raw = String(value).trim();
  if (!raw) return null;
  return getCountryIdByName(raw) ?? raw;
}
