ALTER TABLE matches
  ADD COLUMN IF NOT EXISTS home_yellow_cards INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_red_cards INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_injuries INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_yellow_cards INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_red_cards INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS away_injuries INTEGER NOT NULL DEFAULT 0;

-- DONE!